`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Dec 21 2020 13:30:36 KST (Dec 21 2020 04:30:36 UTC)

module avg_pool_Equal_8Sx7S_1U_4(in2, in1, out1);
  input [7:0] in2;
  input [6:0] in1;
  output out1;
  wire [7:0] in2;
  wire [6:0] in1;
  wire out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9;
  NOR4X1 g99(.A (n_1), .B (n_6), .C (n_8), .D (n_9), .Y (out1));
  NAND4XL g100(.A (n_7), .B (n_2), .C (n_3), .D (n_4), .Y (n_9));
  NAND2X1 g101(.A (n_5), .B (n_0), .Y (n_8));
  XNOR2X1 g107(.A (in2[7]), .B (in1[6]), .Y (n_7));
  XOR2XL g103(.A (in2[5]), .B (in1[5]), .Y (n_6));
  XNOR2X1 g106(.A (in2[1]), .B (in1[1]), .Y (n_5));
  XNOR2X1 g108(.A (in2[2]), .B (in1[2]), .Y (n_4));
  XNOR2X1 g102(.A (in2[3]), .B (in1[3]), .Y (n_3));
  XNOR2X1 g109(.A (in2[4]), .B (in1[4]), .Y (n_2));
  XOR2XL g104(.A (in2[6]), .B (in1[6]), .Y (n_1));
  XNOR2X1 g105(.A (in2[0]), .B (in1[0]), .Y (n_0));
endmodule

