`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Jan  8 2021 16:54:51 KST (Jan  8 2021 07:54:51 UTC)

module bias_add_N_Mux_2_2_3_4_0(in3, in2, ctrl1, out1);
  input [1:0] in3, in2;
  input ctrl1;
  output [1:0] out1;
  wire [1:0] in3, in2;
  wire ctrl1;
  wire [1:0] out1;
  MX2XL g21(.A (in3[1]), .B (in2[1]), .S0 (ctrl1), .Y (out1[1]));
  MX2XL g22(.A (in3[0]), .B (in2[0]), .S0 (ctrl1), .Y (out1[0]));
endmodule


