`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Dec 28 2020 13:26:13 KST (Dec 28 2020 04:26:13 UTC)

module fix2float_AnyAdd2u8s8_4_0(in2, in1, out1);
  input [7:0] in2, in1;
  output out1;
  wire [7:0] in2, in1;
  wire out1;
  wire add_24_2_n_0, add_24_2_n_1, add_24_2_n_2, add_24_2_n_3,
       add_24_2_n_4, add_24_2_n_5, add_24_2_n_6, add_24_2_n_7;
  wire add_24_2_n_8, add_24_2_n_9, add_24_2_n_10, add_24_2_n_11,
       add_24_2_n_12, add_24_2_n_13, add_24_2_n_14, add_24_2_n_15;
  wire add_24_2_n_16, add_24_2_n_17, add_24_2_n_18, add_24_2_n_19,
       add_24_2_n_20, add_24_2_n_21, add_24_2_n_22, add_24_2_n_24;
  wire add_24_2_n_26, add_24_2_n_28, add_24_2_n_29, add_24_2_n_31,
       add_24_2_n_32, add_24_2_n_34, add_24_2_n_35, add_24_2_n_36;
  wire add_24_2_n_39, add_24_2_n_40, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11;
  OR4X1 g27(.A (n_3), .B (n_2), .C (n_1), .D (n_0), .Y (out1));
  OR4X1 g28(.A (n_11), .B (n_10), .C (n_9), .D (n_8), .Y (n_1));
  OR4X1 g29(.A (n_7), .B (n_6), .C (n_5), .D (n_4), .Y (n_0));
  XNOR2X1 add_24_2_g286(.A (add_24_2_n_14), .B (add_24_2_n_40), .Y
       (n_9));
  XOR2XL add_24_2_g287(.A (in2[7]), .B (add_24_2_n_39), .Y (n_10));
  NOR2BX1 add_24_2_g288(.AN (in2[7]), .B (add_24_2_n_39), .Y (n_11));
  OAI21X1 add_24_2_g289(.A0 (add_24_2_n_7), .A1 (add_24_2_n_34), .B0
       (add_24_2_n_0), .Y (add_24_2_n_40));
  OAI211X1 add_24_2_g290(.A0 (add_24_2_n_0), .A1 (add_24_2_n_6), .B0
       (add_24_2_n_36), .C0 (add_24_2_n_24), .Y (add_24_2_n_39));
  XNOR2X1 add_24_2_g291(.A (add_24_2_n_20), .B (add_24_2_n_35), .Y
       (n_7));
  XNOR2X1 add_24_2_g292(.A (add_24_2_n_19), .B (add_24_2_n_34), .Y
       (n_8));
  AOI31X1 add_24_2_g293(.A0 (add_24_2_n_15), .A1 (add_24_2_n_16), .A2
       (add_24_2_n_32), .B0 (add_24_2_n_5), .Y (add_24_2_n_36));
  OAI21X1 add_24_2_g294(.A0 (add_24_2_n_1), .A1 (add_24_2_n_31), .B0
       (add_24_2_n_2), .Y (add_24_2_n_35));
  AOI21X1 add_24_2_g295(.A0 (add_24_2_n_15), .A1 (add_24_2_n_32), .B0
       (add_24_2_n_21), .Y (add_24_2_n_34));
  XNOR2X1 add_24_2_g296(.A (add_24_2_n_18), .B (add_24_2_n_31), .Y
       (n_6));
  INVX1 add_24_2_g297(.A (add_24_2_n_32), .Y (add_24_2_n_31));
  OAI21X1 add_24_2_g298(.A0 (add_24_2_n_4), .A1 (add_24_2_n_29), .B0
       (add_24_2_n_3), .Y (add_24_2_n_32));
  XNOR2X1 add_24_2_g299(.A (add_24_2_n_17), .B (add_24_2_n_28), .Y
       (n_5));
  AOI21X1 add_24_2_g300(.A0 (add_24_2_n_8), .A1 (add_24_2_n_26), .B0
       (add_24_2_n_10), .Y (add_24_2_n_29));
  OAI2BB1X1 add_24_2_g301(.A0N (add_24_2_n_8), .A1N (add_24_2_n_26),
       .B0 (add_24_2_n_11), .Y (add_24_2_n_28));
  XNOR2X1 add_24_2_g302(.A (add_24_2_n_13), .B (add_24_2_n_26), .Y
       (n_4));
  ADDFX1 add_24_2_g303(.A (add_24_2_n_22), .B (in1[1]), .CI (in2[1]),
       .CO (add_24_2_n_26), .S (n_3));
  NAND2XL add_24_2_g304(.A (add_24_2_n_16), .B (add_24_2_n_21), .Y
       (add_24_2_n_24));
  ADDHX1 add_24_2_g305(.A (in2[0]), .B (in1[0]), .CO (add_24_2_n_22),
       .S (n_2));
  OAI21X1 add_24_2_g306(.A0 (add_24_2_n_2), .A1 (add_24_2_n_9), .B0
       (add_24_2_n_12), .Y (add_24_2_n_21));
  NAND2BXL add_24_2_g307(.AN (add_24_2_n_9), .B (add_24_2_n_12), .Y
       (add_24_2_n_20));
  NOR2BX1 add_24_2_g308(.AN (add_24_2_n_0), .B (add_24_2_n_7), .Y
       (add_24_2_n_19));
  NOR2BX1 add_24_2_g309(.AN (add_24_2_n_2), .B (add_24_2_n_1), .Y
       (add_24_2_n_18));
  NAND2BXL add_24_2_g310(.AN (add_24_2_n_4), .B (add_24_2_n_3), .Y
       (add_24_2_n_17));
  NOR2X1 add_24_2_g311(.A (add_24_2_n_6), .B (add_24_2_n_7), .Y
       (add_24_2_n_16));
  NOR2X1 add_24_2_g312(.A (add_24_2_n_9), .B (add_24_2_n_1), .Y
       (add_24_2_n_15));
  OR2XL add_24_2_g313(.A (add_24_2_n_5), .B (add_24_2_n_6), .Y
       (add_24_2_n_14));
  NAND2XL add_24_2_g314(.A (add_24_2_n_11), .B (add_24_2_n_8), .Y
       (add_24_2_n_13));
  INVX1 add_24_2_g315(.A (add_24_2_n_11), .Y (add_24_2_n_10));
  NAND2X1 add_24_2_g316(.A (in2[5]), .B (in1[5]), .Y (add_24_2_n_12));
  NAND2X1 add_24_2_g317(.A (in2[2]), .B (in1[2]), .Y (add_24_2_n_11));
  NOR2X1 add_24_2_g318(.A (in2[5]), .B (in1[5]), .Y (add_24_2_n_9));
  OR2XL add_24_2_g319(.A (in2[2]), .B (in1[2]), .Y (add_24_2_n_8));
  NOR2X1 add_24_2_g320(.A (in2[6]), .B (in1[6]), .Y (add_24_2_n_7));
  NOR2X1 add_24_2_g321(.A (in2[7]), .B (in1[7]), .Y (add_24_2_n_6));
  AND2X1 add_24_2_g322(.A (in2[7]), .B (in1[7]), .Y (add_24_2_n_5));
  NOR2X1 add_24_2_g323(.A (in2[3]), .B (in1[3]), .Y (add_24_2_n_4));
  NAND2X1 add_24_2_g324(.A (in2[3]), .B (in1[3]), .Y (add_24_2_n_3));
  NAND2X1 add_24_2_g325(.A (in2[4]), .B (in1[4]), .Y (add_24_2_n_2));
  NOR2X1 add_24_2_g326(.A (in2[4]), .B (in1[4]), .Y (add_24_2_n_1));
  NAND2X1 add_24_2_g327(.A (in2[6]), .B (in1[6]), .Y (add_24_2_n_0));
endmodule


