`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Dec 28 2020 13:24:02 KST (Dec 28 2020 04:24:02 UTC)

module fix2float_AnyAdd2u8s8_1(in2, in1, out1);
  input [7:0] in2, in1;
  output out1;
  wire [7:0] in2, in1;
  wire out1;
  wire add_24_2_n_0, add_24_2_n_2, add_24_2_n_3, add_24_2_n_4,
       add_24_2_n_5, add_24_2_n_6, add_24_2_n_7, add_24_2_n_8;
  wire add_24_2_n_9, add_24_2_n_10, add_24_2_n_11, add_24_2_n_12,
       add_24_2_n_13, add_24_2_n_14, add_24_2_n_15, add_24_2_n_16;
  wire add_24_2_n_17, add_24_2_n_18, add_24_2_n_19, add_24_2_n_20,
       add_24_2_n_21, add_24_2_n_22, add_24_2_n_24, add_24_2_n_25;
  wire add_24_2_n_26, add_24_2_n_27, add_24_2_n_28, add_24_2_n_29,
       add_24_2_n_30, add_24_2_n_31, add_24_2_n_32, add_24_2_n_33;
  wire add_24_2_n_34, add_24_2_n_35, add_24_2_n_36, add_24_2_n_38,
       add_24_2_n_39, add_24_2_n_40, add_24_2_n_41, add_24_2_n_42;
  wire add_24_2_n_44, add_24_2_n_46, add_24_2_n_47, add_24_2_n_48,
       add_24_2_n_49, add_24_2_n_50, add_24_2_n_53, add_24_2_n_54;
  wire add_24_2_n_79, add_24_2_n_82, add_24_2_n_85, n_0, n_1, n_2, n_3,
       n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15;
  NAND3X1 g39(.A (n_2), .B (n_4), .C (n_5), .Y (out1));
  NOR2BX1 g40(.AN (n_1), .B (n_0), .Y (n_5));
  NOR3BX1 g41(.AN (n_3), .B (n_10), .C (n_11), .Y (n_4));
  NOR2X1 g42(.A (n_8), .B (n_9), .Y (n_3));
  NOR2X1 g43(.A (n_7), .B (n_6), .Y (n_2));
  NOR2XL g44(.A (n_13), .B (n_12), .Y (n_1));
  OR2XL g45(.A (n_15), .B (n_14), .Y (n_0));
  XNOR2X1 add_24_2_g191(.A (add_24_2_n_28), .B (add_24_2_n_53), .Y
       (n_11));
  XNOR2XL add_24_2_g192(.A (add_24_2_n_21), .B (add_24_2_n_50), .Y
       (n_13));
  XNOR2X1 add_24_2_g193(.A (add_24_2_n_26), .B (add_24_2_n_6), .Y
       (n_12));
  AND2XL add_24_2_g194(.A (in2[7]), .B (add_24_2_n_54), .Y (n_15));
  NOR2X1 add_24_2_g195(.A (add_24_2_n_39), .B (add_24_2_n_48), .Y
       (add_24_2_n_54));
  AOI21X2 add_24_2_g197(.A0 (add_24_2_n_82), .A1 (add_24_2_n_79), .B0
       (add_24_2_n_19), .Y (add_24_2_n_53));
  XNOR2X1 add_24_2_g198(.A (add_24_2_n_27), .B (add_24_2_n_79), .Y
       (n_10));
  XNOR2X1 add_24_2_g199(.A (add_24_2_n_30), .B (add_24_2_n_46), .Y
       (n_9));
  NOR2X1 add_24_2_g200(.A (add_24_2_n_40), .B (add_24_2_n_47), .Y
       (add_24_2_n_50));
  NOR2X1 add_24_2_g201(.A (add_24_2_n_4), .B (add_24_2_n_44), .Y
       (add_24_2_n_49));
  NOR2X1 add_24_2_g202(.A (add_24_2_n_35), .B (add_24_2_n_44), .Y
       (add_24_2_n_48));
  NOR2X1 add_24_2_g203(.A (add_24_2_n_34), .B (add_24_2_n_44), .Y
       (add_24_2_n_47));
  AOI21X2 add_24_2_g204(.A0 (add_24_2_n_0), .A1 (add_24_2_n_41), .B0
       (add_24_2_n_14), .Y (add_24_2_n_46));
  XNOR2X1 add_24_2_g205(.A (add_24_2_n_22), .B (add_24_2_n_41), .Y
       (n_8));
  NOR2X4 add_24_2_g207(.A (add_24_2_n_31), .B (add_24_2_n_42), .Y
       (add_24_2_n_44));
  NOR2X2 add_24_2_g208(.A (add_24_2_n_5), .B (add_24_2_n_38), .Y
       (add_24_2_n_42));
  INVX1 add_24_2_g209(.A (add_24_2_n_38), .Y (add_24_2_n_41));
  OAI21X1 add_24_2_g210(.A0 (add_24_2_n_12), .A1 (add_24_2_n_33), .B0
       (add_24_2_n_15), .Y (add_24_2_n_40));
  OAI21X1 add_24_2_g211(.A0 (add_24_2_n_25), .A1 (add_24_2_n_33), .B0
       (add_24_2_n_32), .Y (add_24_2_n_39));
  NOR2X2 add_24_2_g212(.A (add_24_2_n_3), .B (add_24_2_n_36), .Y
       (add_24_2_n_38));
  XNOR2X1 add_24_2_g213(.A (add_24_2_n_8), .B (add_24_2_n_29), .Y
       (n_7));
  NOR2X2 add_24_2_g214(.A (add_24_2_n_9), .B (add_24_2_n_8), .Y
       (add_24_2_n_36));
  OR2XL add_24_2_g215(.A (add_24_2_n_25), .B (add_24_2_n_4), .Y
       (add_24_2_n_35));
  OR2XL add_24_2_g216(.A (add_24_2_n_12), .B (add_24_2_n_4), .Y
       (add_24_2_n_34));
  NOR2X1 add_24_2_g218(.A (add_24_2_n_11), .B (add_24_2_n_24), .Y
       (add_24_2_n_33));
  OA21X1 add_24_2_g219(.A0 (add_24_2_n_15), .A1 (add_24_2_n_17), .B0
       (add_24_2_n_20), .Y (add_24_2_n_32));
  OAI21X1 add_24_2_g220(.A0 (add_24_2_n_16), .A1 (add_24_2_n_13), .B0
       (add_24_2_n_10), .Y (add_24_2_n_31));
  NOR2BX1 add_24_2_g222(.AN (add_24_2_n_10), .B (add_24_2_n_85), .Y
       (add_24_2_n_30));
  NOR2X1 add_24_2_g223(.A (add_24_2_n_3), .B (add_24_2_n_9), .Y
       (add_24_2_n_29));
  NOR2X1 add_24_2_g224(.A (add_24_2_n_11), .B (add_24_2_n_7), .Y
       (add_24_2_n_28));
  NAND2XL add_24_2_g225(.A (add_24_2_n_18), .B (add_24_2_n_82), .Y
       (add_24_2_n_27));
  NOR2BX1 add_24_2_g226(.AN (add_24_2_n_15), .B (add_24_2_n_12), .Y
       (add_24_2_n_26));
  NOR2X1 add_24_2_g227(.A (add_24_2_n_18), .B (add_24_2_n_7), .Y
       (add_24_2_n_24));
  XOR2XL add_24_2_g228(.A (in2[0]), .B (in1[0]), .Y (n_6));
  NAND2XL add_24_2_g229(.A (add_24_2_n_13), .B (add_24_2_n_0), .Y
       (add_24_2_n_22));
  NOR2BX1 add_24_2_g230(.AN (add_24_2_n_20), .B (add_24_2_n_17), .Y
       (add_24_2_n_21));
  OR2XL add_24_2_g231(.A (add_24_2_n_17), .B (add_24_2_n_12), .Y
       (add_24_2_n_25));
  INVX1 add_24_2_g233(.A (add_24_2_n_18), .Y (add_24_2_n_19));
  INVX1 add_24_2_g235(.A (add_24_2_n_13), .Y (add_24_2_n_14));
  NAND2X1 add_24_2_g236(.A (in2[7]), .B (in1[7]), .Y (add_24_2_n_20));
  NAND2X1 add_24_2_g237(.A (in2[4]), .B (in1[4]), .Y (add_24_2_n_18));
  NOR2X1 add_24_2_g238(.A (in2[7]), .B (in1[7]), .Y (add_24_2_n_17));
  NOR2X4 add_24_2_g239(.A (in2[3]), .B (in1[3]), .Y (add_24_2_n_16));
  NAND2X1 add_24_2_g240(.A (in2[6]), .B (in1[6]), .Y (add_24_2_n_15));
  NAND2X2 add_24_2_g241(.A (in2[2]), .B (in1[2]), .Y (add_24_2_n_13));
  NOR2X1 add_24_2_g242(.A (in2[6]), .B (in1[6]), .Y (add_24_2_n_12));
  AND2X1 add_24_2_g244(.A (in2[5]), .B (in1[5]), .Y (add_24_2_n_11));
  NAND2X1 add_24_2_g245(.A (in2[3]), .B (in1[3]), .Y (add_24_2_n_10));
  NOR2X4 add_24_2_g246(.A (in2[1]), .B (in1[1]), .Y (add_24_2_n_9));
  NAND2X8 add_24_2_g248(.A (in2[0]), .B (in1[0]), .Y (add_24_2_n_8));
  NOR2X1 add_24_2_g251(.A (in2[5]), .B (in1[5]), .Y (add_24_2_n_7));
  NOR2BX1 add_24_2_g2(.AN (add_24_2_n_33), .B (add_24_2_n_49), .Y
       (add_24_2_n_6));
  NAND2BX4 add_24_2_g259(.AN (add_24_2_n_16), .B (add_24_2_n_0), .Y
       (add_24_2_n_5));
  NAND2BX1 add_24_2_g260(.AN (add_24_2_n_7), .B (add_24_2_n_2), .Y
       (add_24_2_n_4));
  CLKAND2X3 add_24_2_g261(.A (in2[1]), .B (in1[1]), .Y (add_24_2_n_3));
  OR2X1 add_24_2_g262(.A (in2[4]), .B (in1[4]), .Y (add_24_2_n_2));
  XNOR2XL add_24_2_g263(.A (in2[7]), .B (add_24_2_n_54), .Y (n_14));
  OR2X6 add_24_2_g264(.A (in2[2]), .B (in1[2]), .Y (add_24_2_n_0));
  CLKINVX1 add_24_2_fopt(.A (add_24_2_n_44), .Y (add_24_2_n_79));
  BUFX3 add_24_2_fopt265(.A (add_24_2_n_2), .Y (add_24_2_n_82));
  BUFX2 add_24_2_fopt266(.A (add_24_2_n_16), .Y (add_24_2_n_85));
endmodule


