`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Dec 28 2020 13:43:23 KST (Dec 28 2020 04:43:23 UTC)

module fix2float_Subu8i127_4_2(in1, out1);
  input [7:0] in1;
  output [7:0] out1;
  wire [7:0] in1;
  wire [7:0] out1;
  assign out1[7] = in1[7];
  INVX1 g18(.A (in1[6]), .Y (out1[6]));
  INVX1 g15(.A (in1[5]), .Y (out1[5]));
  INVX1 g17(.A (in1[3]), .Y (out1[3]));
  INVX1 g12(.A (in1[1]), .Y (out1[1]));
  INVX1 g16(.A (in1[4]), .Y (out1[4]));
  INVX1 g14(.A (in1[2]), .Y (out1[2]));
  INVX1 g13(.A (in1[0]), .Y (out1[0]));
endmodule


