`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Jan  7 2021 15:40:58 KST (Jan  7 2021 06:40:58 UTC)

module float2fix_Gti31s9_1(in1, out1);
  input [8:0] in1;
  output out1;
  wire [8:0] in1;
  wire out1;
  wire gt_19_59_n_33;
  NOR2X2 gt_19_59_g2(.A (in1[8]), .B (gt_19_59_n_33), .Y (out1));
  NOR3X8 gt_19_59_g3(.A (in1[5]), .B (in1[7]), .C (in1[6]), .Y
       (gt_19_59_n_33));
endmodule


