`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Dec 23 2020 14:43:31 KST (Dec 23 2020 05:43:31 UTC)

module in_buff_Equal_3Ux2U_1U_1(in2, in1, out1);
  input [2:0] in2;
  input [1:0] in1;
  output out1;
  wire [2:0] in2;
  wire [1:0] in1;
  wire out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9;
  NOR3X2 g36(.A (in2[2]), .B (n_9), .C (n_8), .Y (out1));
  NOR2X2 g37(.A (n_5), .B (n_7), .Y (n_9));
  NOR2X1 g38(.A (n_4), .B (n_6), .Y (n_8));
  NOR2X6 g40(.A (n_0), .B (n_3), .Y (n_7));
  NOR2X2 g41(.A (n_2), .B (n_1), .Y (n_6));
  NOR2X2 g39(.A (in2[1]), .B (in1[1]), .Y (n_5));
  NOR2X1 g42(.A (in2[0]), .B (in1[0]), .Y (n_4));
  CLKINVX4 g43(.A (in1[1]), .Y (n_3));
  INVX2 g44(.A (in2[0]), .Y (n_2));
  INVX1 g45(.A (in1[0]), .Y (n_1));
  CLKINVX12 g46(.A (in2[1]), .Y (n_0));
endmodule


