`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Jan 11 2021 20:25:35 KST (Jan 11 2021 11:25:35 UTC)

module sfu_out_buff_MuxAdd2i1u2i0u1_4_0(in2, ctrl1, out1);
  input [1:0] in2;
  input ctrl1;
  output [1:0] out1;
  wire [1:0] in2;
  wire ctrl1;
  wire [1:0] out1;
  wire n_0;
  AND2XL g26(.A (ctrl1), .B (n_0), .Y (out1[1]));
  NOR2BX1 g27(.AN (ctrl1), .B (in2[0]), .Y (out1[0]));
  XOR2XL inc_add_24_2_g11(.A (in2[1]), .B (in2[0]), .Y (n_0));
endmodule


