// Generated by stratus_hls 19.10-p100  (91500.011111)
// Sun Jan 17 14:37:37 2021
// from fp_cmp.cpp
#ifndef CYNTH_PART_fp_cmp_fp_cmp_rtl_h
#define CYNTH_PART_fp_cmp_fp_cmp_rtl_h

#include "systemc.h"
/* Include declarations of instantiated parts. */


/* Declaration of the synthesized module. */
struct fp_cmp : public sc_module {
  sc_in<bool > clk;
  sc_in<bool > rstn;
  sc_in<bool > enable;
  sc_in<bool > src_valid;
  sc_in<sc_uint<23> > a_man;
  sc_in<sc_uint<8> > a_exp;
  sc_in<sc_uint<1> > a_sign;
  sc_in<sc_uint<23> > b_man;
  sc_in<sc_uint<8> > b_exp;
  sc_in<sc_uint<1> > b_sign;
  sc_out<sc_uint<23> > r_man;
  sc_out<sc_uint<8> > r_exp;
  sc_out<sc_uint<1> > r_sign;
  sc_out<bool > dst_valid;
  fp_cmp( sc_module_name name );
  SC_HAS_PROCESS(fp_cmp);
  sc_signal<sc_uint<1> > fp_cmp_cynw_cm_float_ltle_4_1_amtmp032;
  sc_signal<sc_uint<1> > fp_cmp_cynw_cm_float_ltle_4_1_amtmp010;
  sc_signal<sc_biguint<31> > fp_cmp_cynw_cm_float_ltle_4_1_amtmp007;
  sc_signal<sc_biguint<31> > fp_cmp_cynw_cm_float_ltle_alt0_1_3_amtmp012;
  sc_signal<sc_uint<1> > fp_cmp_cynw_cm_float_ltle_alt0_1_3_amtmp038;
  sc_signal<sc_uint<1> > fp_cmp_cynw_cm_float_ltle_alt0_1_3_amtmp033;
  sc_signal<sc_uint<1> > fp_cmp_cynw_cm_float_ltle_alt0_1_3_amtmp026;
  sc_signal<sc_uint<1> > fp_cmp_cynw_cm_float_ltle_alt0_1_3_amtmp014;
  sc_signal<sc_uint<1> > fp_cmp_Muxi0u1u1_4_10_out1;
  sc_signal<sc_uint<8> > fp_cmp_Muxi0u8u1_4_9_out1;
  sc_signal<sc_uint<23> > fp_cmp_Muxi0u23u1_4_8_out1;
  sc_signal<sc_uint<1> > fp_cmp_N_Mux_1_2_2_4_7_out1;
  sc_signal<sc_uint<8> > fp_cmp_N_Mux_8_2_4_4_6_out1;
  sc_signal<sc_uint<23> > fp_cmp_N_Mux_23_2_6_4_5_out1;
  sc_signal<sc_uint<1> > fp_cmp_OrReduction_2S_1U_4_4_out1;
  sc_signal<sc_int<2> > fp_cmp_cynw_cm_float_ltle_alt0_1_3_out1;
  sc_signal<sc_uint<1> > fp_cmp_cynw_cm_float_ltle_alt0_1_3_amtmp013;
  sc_signal<sc_uint<1> > u_572;
  sc_signal<sc_uint<1> > fp_cmp_cynw_cm_float_ltle_alt0_1_3_ocbSign_i0_u0;
  sc_signal<sc_uint<1> > fp_cmp_cynw_cm_float_ltle_alt0_1_3_ocaSign_i0_u0;
  sc_signal<sc_uint<1> > fp_cmp_OrReduction_2S_1U_4_2_out1;
  sc_signal<sc_int<2> > fp_cmp_cynw_cm_float_ltle_4_1_out1;
  sc_signal<sc_uint<1> > fp_cmp_cynw_cm_float_ltle_4_1_amtmp009;
  sc_signal<sc_uint<1> > u_573;
  sc_signal<sc_uint<1> > fp_cmp_cynw_cm_float_ltle_4_1_ocaSign_u0;
  sc_signal<sc_uint<23> > fp_cmp_N_Mux_23_2_6_4_11_out1;
  sc_signal<sc_uint<8> > fp_cmp_N_Mux_8_2_4_4_12_out1;
  sc_signal<sc_uint<1> > fp_cmp_N_Mux_1_2_2_4_13_out1;
  void drive_dst_valid();
  void drive_r_sign();
  void drive_r_exp();
  void drive_r_man();
  void fp_cmp_cynw_cm_float_ltle_4_1_p10();
  void fp_cmp_OrReduction_2S_1U_4_2();
  void fp_cmp_cynw_cm_float_ltle_alt0_1_3_p10();
  void fp_cmp_OrReduction_2S_1U_4_4();
  void fp_cmp_N_Mux_23_2_6_4_5();
  void fp_cmp_N_Mux_8_2_4_4_6();
  void fp_cmp_N_Mux_1_2_2_4_7();
  void fp_cmp_Muxi0u23u1_4_8();
  void fp_cmp_Muxi0u8u1_4_9();
  void fp_cmp_Muxi0u1u1_4_10();
  void fp_cmp_N_Mux_23_2_6_4_11();
  void fp_cmp_N_Mux_8_2_4_4_12();
  void fp_cmp_N_Mux_1_2_2_4_13();
  void fp_cmp_cynw_cm_float_ltle_alt0_1_3_p5();
  void fp_cmp_cynw_cm_float_ltle_alt0_1_3_p2();
  void fp_cmp_cynw_cm_float_ltle_alt0_1_3_p9();
  void fp_cmp_cynw_cm_float_ltle_alt0_1_3_p8();
  void fp_cmp_cynw_cm_float_ltle_alt0_1_3_p7();
  void fp_cmp_cynw_cm_float_ltle_alt0_1_3_p6();
  void fp_cmp_cynw_cm_float_ltle_alt0_1_3_p4();
  void fp_cmp_cynw_cm_float_ltle_alt0_1_3_p3();
  void mux_572();
  void fp_cmp_cynw_cm_float_ltle_4_1_p5();
  void fp_cmp_cynw_cm_float_ltle_4_1_p3();
  void fp_cmp_cynw_cm_float_ltle_4_1_p9();
  void fp_cmp_cynw_cm_float_ltle_4_1_p7();
  void fp_cmp_cynw_cm_float_ltle_4_1_p2();
  void mux_573();
};

#endif
