// Generated by stratus_hls 19.10-p100  (91500.011111)
// Wed Dec 16 18:22:49 2020
// from feature_write_addr_gen.cpp
#include "feature_write_addr_gen_rtl.h"

struct feature_write_addr_gen;
feature_write_addr_gen::feature_write_addr_gen(sc_module_name name) : sc_module(name) 
    ,clk("clk")
    ,rstn("rstn")
    ,init("init")
    ,start("start")
    ,stop("stop")
    ,base_addr("base_addr")
    ,src("src")
    ,src_vld("src_vld")
    ,read_address("read_address")
    ,read_address_valid("read_address_valid")
    ,read_data("read_data")
    ,address_0("address_0")
    ,cs_0("cs_0")
    ,we_0("we_0")
    ,oe_0("oe_0")
    ,data_in("data_in")
    ,data_out("data_out")
    ,feature_write_addr_gen_N_Mux_32_2_6_4_39_out1("feature_write_addr_gen_N_Mux_32_2_6_4_39_out1")
    ,feature_write_addr_gen_Not_1U_1U_4_37_out1("feature_write_addr_gen_Not_1U_1U_4_37_out1")
    ,feature_write_addr_gen_Or_1Ux1U_1U_4_35_out1("feature_write_addr_gen_Or_1Ux1U_1U_4_35_out1")
    ,feature_write_addr_gen_Not_1U_1U_4_34_out1("feature_write_addr_gen_Not_1U_1U_4_34_out1")
    ,feature_write_addr_gen_OrReduction_3U_1U_4_36_out1("feature_write_addr_gen_OrReduction_3U_1U_4_36_out1")
    ,fifo_cnt_1d("fifo_cnt_1d")
    ,feature_write_addr_gen_N_MuxB_320_2_5_4_41_out1("feature_write_addr_gen_N_MuxB_320_2_5_4_41_out1")
    ,feature_write_addr_gen_N_Mux_32_2_2_4_44_out1("feature_write_addr_gen_N_Mux_32_2_2_4_44_out1")
    ,feature_write_addr_gen_Or_1Ux1U_1U_4_43_out1("feature_write_addr_gen_Or_1Ux1U_1U_4_43_out1")
    ,feature_write_addr_gen_And_1Ux1U_1U_4_42_out1("feature_write_addr_gen_And_1Ux1U_1U_4_42_out1")
    ,feature_write_addr_gen_N_MuxB_320_2_4_4_40_out1("feature_write_addr_gen_N_MuxB_320_2_4_4_40_out1")
    ,feature_write_addr_gen_Add_32Ux32U_32U_1_16_out1("feature_write_addr_gen_Add_32Ux32U_32U_1_16_out1")
    ,feature_write_addr_gen_N_Mux_32_2_2_4_46_out1("feature_write_addr_gen_N_Mux_32_2_2_4_46_out1")
    ,feature_write_addr_gen_Add_32Ux1U_32U_4_45_out1("feature_write_addr_gen_Add_32Ux1U_32U_4_45_out1")
    ,feature_write_addr_gen_N_Mux_32_2_3_4_47_out1("feature_write_addr_gen_N_Mux_32_2_3_4_47_out1")
    ,write_cnt("write_cnt")
    ,feature_write_addr_gen_OrReduction_3U_1U_4_7_out1("feature_write_addr_gen_OrReduction_3U_1U_4_7_out1")
    ,feature_write_addr_gen_NotEQ_3Ux3U_1U_4_5_out1("feature_write_addr_gen_NotEQ_3Ux3U_1U_4_5_out1")
    ,feature_write_addr_gen_Equal_3Ux3U_1U_4_8_out1("feature_write_addr_gen_Equal_3Ux3U_1U_4_8_out1")
    ,feature_write_addr_gen_Equal_3Ux3U_1U_4_9_out1("feature_write_addr_gen_Equal_3Ux3U_1U_4_9_out1")
    ,feature_write_addr_gen_Equal_3Ux3U_1U_4_10_out1("feature_write_addr_gen_Equal_3Ux3U_1U_4_10_out1")
    ,feature_write_addr_gen_Equal_3Ux3U_1U_4_11_out1("feature_write_addr_gen_Equal_3Ux3U_1U_4_11_out1")
    ,feature_write_addr_gen_Equal_3Ux2U_1U_4_12_out1("feature_write_addr_gen_Equal_3Ux2U_1U_4_12_out1")
    ,feature_write_addr_gen_Equal_3Ux2U_1U_4_13_out1("feature_write_addr_gen_Equal_3Ux2U_1U_4_13_out1")
    ,feature_write_addr_gen_Equal_3Ux1U_1U_4_14_out1("feature_write_addr_gen_Equal_3Ux1U_1U_4_14_out1")
    ,feature_write_addr_gen_And_1Ux1U_1U_4_6_out1("feature_write_addr_gen_And_1Ux1U_1U_4_6_out1")
    ,feature_write_addr_gen_Not_1U_1U_4_15_out1("feature_write_addr_gen_Not_1U_1U_4_15_out1")
    ,fifo_mem_7("fifo_mem_7")
    ,fifo_mem_0("fifo_mem_0")
    ,fifo_mem_1("fifo_mem_1")
    ,fifo_mem_2("fifo_mem_2")
    ,fifo_mem_3("fifo_mem_3")
    ,fifo_mem_4("fifo_mem_4")
    ,fifo_mem_5("fifo_mem_5")
    ,fifo_mem_6("fifo_mem_6")
    ,feature_write_addr_gen_OrReduction_3U_1U_4_30_out1("feature_write_addr_gen_OrReduction_3U_1U_4_30_out1")
    ,fifo_out("fifo_out")
    ,feature_write_addr_gen_And_1Ux1U_1U_4_31_out1("feature_write_addr_gen_And_1Ux1U_1U_4_31_out1")
    ,feature_write_addr_gen_N_MuxB_320_8_1_1_32_out1("feature_write_addr_gen_N_MuxB_320_8_1_1_32_out1")
    ,feature_write_addr_gen_N_Mux_3_2_0_4_22_out1("feature_write_addr_gen_N_Mux_3_2_0_4_22_out1")
    ,feature_write_addr_gen_Add_3Ux1U_3U_4_21_out1("feature_write_addr_gen_Add_3Ux1U_3U_4_21_out1")
    ,feature_write_addr_gen_Sub_3Ux1U_3S_4_20_out1("feature_write_addr_gen_Sub_3Ux1U_3S_4_20_out1")
    ,feature_write_addr_gen_And_1Ux1U_1U_4_19_out1("feature_write_addr_gen_And_1Ux1U_1U_4_19_out1")
    ,feature_write_addr_gen_OrReduction_3U_1U_4_18_out1("feature_write_addr_gen_OrReduction_3U_1U_4_18_out1")
    ,feature_write_addr_gen_N_Mux_3_2_0_4_23_out1("feature_write_addr_gen_N_Mux_3_2_0_4_23_out1")
    ,feature_write_addr_gen_Not_1U_1U_1_17_out1("feature_write_addr_gen_Not_1U_1U_1_17_out1")
    ,feature_write_addr_gen_OrReduction_3U_1U_1_24_out1("feature_write_addr_gen_OrReduction_3U_1U_1_24_out1")
    ,feature_write_addr_gen_Add_3Ux1U_3U_4_3_out1("feature_write_addr_gen_Add_3Ux1U_3U_4_3_out1")
    ,feature_write_addr_gen_And_1Ux1U_1U_4_2_out1("feature_write_addr_gen_And_1Ux1U_1U_4_2_out1")
    ,feature_write_addr_gen_NotEQ_3Ux3U_1U_4_1_out1("feature_write_addr_gen_NotEQ_3Ux3U_1U_4_1_out1")
    ,feature_write_addr_gen_N_Mux_3_2_0_4_4_out1("feature_write_addr_gen_N_Mux_3_2_0_4_4_out1")
    ,wr_ptr("wr_ptr")
    ,feature_write_addr_gen_Add_3Ux1U_3U_4_28_out1("feature_write_addr_gen_Add_3Ux1U_3U_4_28_out1")
    ,feature_write_addr_gen_And_1Ux1U_1U_4_27_out1("feature_write_addr_gen_And_1Ux1U_1U_4_27_out1")
    ,feature_write_addr_gen_And_1Ux1U_1U_1_25_out1("feature_write_addr_gen_And_1Ux1U_1U_1_25_out1")
    ,feature_write_addr_gen_OrReduction_3U_1U_4_26_out1("feature_write_addr_gen_OrReduction_3U_1U_4_26_out1")
    ,fifo_cnt("fifo_cnt")
    ,feature_write_addr_gen_N_Mux_3_2_0_4_29_out1("feature_write_addr_gen_N_Mux_3_2_0_4_29_out1")
    ,rd_ptr("rd_ptr")
{
  SC_METHOD(drive_rd_ptr);
  sensitive << clk.pos();
  sensitive << rstn.neg();
  dont_initialize();

  SC_METHOD(feature_write_addr_gen_OrReduction_3U_1U_4_26);
  sensitive << ( fifo_cnt );

  SC_METHOD(feature_write_addr_gen_And_1Ux1U_1U_4_27);
  sensitive << ( feature_write_addr_gen_OrReduction_3U_1U_4_26_out1 );
  sensitive << ( feature_write_addr_gen_And_1Ux1U_1U_1_25_out1 );

  SC_METHOD(feature_write_addr_gen_Add_3Ux1U_3U_4_28);
  sensitive << ( rd_ptr );

  SC_METHOD(feature_write_addr_gen_N_Mux_3_2_0_4_29);
  sensitive << ( feature_write_addr_gen_And_1Ux1U_1U_4_27_out1 );
  sensitive << ( feature_write_addr_gen_Add_3Ux1U_3U_4_28_out1 );
  sensitive << ( rd_ptr );

  SC_METHOD(drive_wr_ptr);
  sensitive << clk.pos();
  sensitive << rstn.neg();
  dont_initialize();

  SC_METHOD(feature_write_addr_gen_NotEQ_3Ux3U_1U_4_1);
  sensitive << ( fifo_cnt );

  SC_METHOD(feature_write_addr_gen_And_1Ux1U_1U_4_2);
  sensitive << ( src_vld );
  sensitive << ( feature_write_addr_gen_NotEQ_3Ux3U_1U_4_1_out1 );

  SC_METHOD(feature_write_addr_gen_Add_3Ux1U_3U_4_3);
  sensitive << ( wr_ptr );

  SC_METHOD(feature_write_addr_gen_N_Mux_3_2_0_4_4);
  sensitive << ( feature_write_addr_gen_And_1Ux1U_1U_4_2_out1 );
  sensitive << ( feature_write_addr_gen_Add_3Ux1U_3U_4_3_out1 );
  sensitive << ( wr_ptr );

  SC_METHOD(feature_write_addr_gen_OrReduction_3U_1U_1_24);
  sensitive << ( fifo_cnt );

  SC_METHOD(feature_write_addr_gen_And_1Ux1U_1U_1_25);
  sensitive << ( feature_write_addr_gen_Not_1U_1U_1_17_out1 );
  sensitive << ( feature_write_addr_gen_OrReduction_3U_1U_1_24_out1 );

  SC_METHOD(drive_fifo_cnt);
  sensitive << clk.pos();
  sensitive << rstn.neg();
  dont_initialize();

  SC_METHOD(feature_write_addr_gen_OrReduction_3U_1U_4_18);
  sensitive << ( fifo_cnt );

  SC_METHOD(feature_write_addr_gen_And_1Ux1U_1U_4_19);
  sensitive << ( feature_write_addr_gen_Not_1U_1U_1_17_out1 );
  sensitive << ( feature_write_addr_gen_OrReduction_3U_1U_4_18_out1 );

  SC_METHOD(feature_write_addr_gen_Sub_3Ux1U_3S_4_20);
  sensitive << ( fifo_cnt );

  SC_METHOD(feature_write_addr_gen_Add_3Ux1U_3U_4_21);
  sensitive << ( fifo_cnt );

  SC_METHOD(feature_write_addr_gen_N_Mux_3_2_0_4_22);
  sensitive << ( feature_write_addr_gen_And_1Ux1U_1U_4_19_out1 );
  sensitive << ( feature_write_addr_gen_Sub_3Ux1U_3S_4_20_out1 );
  sensitive << ( fifo_cnt );

  SC_METHOD(feature_write_addr_gen_N_Mux_3_2_0_4_23);
  sensitive << ( src_vld );
  sensitive << ( feature_write_addr_gen_Add_3Ux1U_3U_4_21_out1 );
  sensitive << ( feature_write_addr_gen_N_Mux_3_2_0_4_22_out1 );

  SC_METHOD(drive_fifo_out);
  sensitive << ( feature_write_addr_gen_And_1Ux1U_1U_4_31_out1 );
  sensitive << ( feature_write_addr_gen_N_MuxB_320_8_1_1_32_out1 );

  SC_METHOD(feature_write_addr_gen_OrReduction_3U_1U_4_30);
  sensitive << ( fifo_cnt );

  SC_METHOD(feature_write_addr_gen_And_1Ux1U_1U_4_31);
  sensitive << ( feature_write_addr_gen_OrReduction_3U_1U_4_30_out1 );
  sensitive << ( feature_write_addr_gen_And_1Ux1U_1U_1_25_out1 );

  SC_METHOD(feature_write_addr_gen_N_MuxB_320_8_1_1_32);
  sensitive << ( rd_ptr );
  sensitive << ( fifo_mem_7 );
  sensitive << ( fifo_mem_0 );
  sensitive << ( fifo_mem_1 );
  sensitive << ( fifo_mem_2 );
  sensitive << ( fifo_mem_3 );
  sensitive << ( fifo_mem_4 );
  sensitive << ( fifo_mem_5 );
  sensitive << ( fifo_mem_6 );

  SC_METHOD(drive_fifo_mem_0);
  sensitive << clk.pos();
  sensitive << rstn.neg();
  dont_initialize();

  SC_METHOD(drive_fifo_mem_1);
  sensitive << clk.pos();
  sensitive << rstn.neg();
  dont_initialize();

  SC_METHOD(drive_fifo_mem_2);
  sensitive << clk.pos();
  sensitive << rstn.neg();
  dont_initialize();

  SC_METHOD(drive_fifo_mem_3);
  sensitive << clk.pos();
  sensitive << rstn.neg();
  dont_initialize();

  SC_METHOD(drive_fifo_mem_4);
  sensitive << clk.pos();
  sensitive << rstn.neg();
  dont_initialize();

  SC_METHOD(drive_fifo_mem_5);
  sensitive << clk.pos();
  sensitive << rstn.neg();
  dont_initialize();

  SC_METHOD(drive_fifo_mem_6);
  sensitive << clk.pos();
  sensitive << rstn.neg();
  dont_initialize();

  SC_METHOD(drive_fifo_mem_7);
  sensitive << clk.pos();
  sensitive << rstn.neg();
  dont_initialize();

  SC_METHOD(feature_write_addr_gen_NotEQ_3Ux3U_1U_4_5);
  sensitive << ( fifo_cnt );

  SC_METHOD(feature_write_addr_gen_And_1Ux1U_1U_4_6);
  sensitive << ( src_vld );
  sensitive << ( feature_write_addr_gen_NotEQ_3Ux3U_1U_4_5_out1 );

  SC_METHOD(feature_write_addr_gen_OrReduction_3U_1U_4_7);
  sensitive << ( wr_ptr );

  SC_METHOD(feature_write_addr_gen_Equal_3Ux3U_1U_4_8);
  sensitive << ( wr_ptr );

  SC_METHOD(feature_write_addr_gen_Equal_3Ux3U_1U_4_9);
  sensitive << ( wr_ptr );

  SC_METHOD(feature_write_addr_gen_Equal_3Ux3U_1U_4_10);
  sensitive << ( wr_ptr );

  SC_METHOD(feature_write_addr_gen_Equal_3Ux3U_1U_4_11);
  sensitive << ( wr_ptr );

  SC_METHOD(feature_write_addr_gen_Equal_3Ux2U_1U_4_12);
  sensitive << ( wr_ptr );

  SC_METHOD(feature_write_addr_gen_Equal_3Ux2U_1U_4_13);
  sensitive << ( wr_ptr );

  SC_METHOD(feature_write_addr_gen_Equal_3Ux1U_1U_4_14);
  sensitive << ( wr_ptr );

  SC_METHOD(feature_write_addr_gen_Not_1U_1U_4_15);
  sensitive << ( feature_write_addr_gen_OrReduction_3U_1U_4_7_out1 );

  SC_METHOD(drive_write_cnt);
  sensitive << clk.pos();
  sensitive << rstn.neg();
  dont_initialize();

  SC_METHOD(feature_write_addr_gen_Add_32Ux1U_32U_4_45);
  sensitive << ( write_cnt );

  SC_METHOD(feature_write_addr_gen_N_Mux_32_2_2_4_46);
  sensitive << ( we_0 );
  sensitive << ( feature_write_addr_gen_Add_32Ux1U_32U_4_45_out1 );
  sensitive << ( write_cnt );

  SC_METHOD(feature_write_addr_gen_N_Mux_32_2_3_4_47);
  sensitive << ( init );
  sensitive << ( feature_write_addr_gen_N_Mux_32_2_2_4_46_out1 );

  SC_METHOD(feature_write_addr_gen_Add_32Ux32U_32U_1_16);
  sensitive << ( base_addr );
  sensitive << ( write_cnt );

  SC_METHOD(drive_stop);
  sensitive << ( src_vld );

  SC_METHOD(drive_data_out);
  sensitive << ( feature_write_addr_gen_N_MuxB_320_2_4_4_40_out1 );

  SC_METHOD(drive_oe_0);
  sensitive << ( read_address_valid );

  SC_METHOD(drive_we_0);
  sensitive << ( feature_write_addr_gen_And_1Ux1U_1U_4_42_out1 );

  SC_METHOD(drive_cs_0);
  sensitive << ( feature_write_addr_gen_Or_1Ux1U_1U_4_43_out1 );

  SC_METHOD(drive_address_0);
  sensitive << ( feature_write_addr_gen_N_Mux_32_2_2_4_44_out1 );

  SC_METHOD(drive_read_data);
  sensitive << ( feature_write_addr_gen_N_MuxB_320_2_5_4_41_out1 );

  SC_METHOD(feature_write_addr_gen_OrReduction_3U_1U_4_36);
  sensitive << ( fifo_cnt_1d );

  SC_METHOD(feature_write_addr_gen_Not_1U_1U_4_34);
  sensitive << ( feature_write_addr_gen_OrReduction_3U_1U_4_36_out1 );

  SC_METHOD(feature_write_addr_gen_Or_1Ux1U_1U_4_35);
  sensitive << ( read_address_valid );
  sensitive << ( feature_write_addr_gen_Not_1U_1U_4_34_out1 );

  SC_METHOD(feature_write_addr_gen_Not_1U_1U_4_37);
  sensitive << ( read_address_valid );

  SC_METHOD(feature_write_addr_gen_N_Mux_32_2_6_4_39);
  sensitive << ( feature_write_addr_gen_OrReduction_3U_1U_4_36_out1 );
  sensitive << ( feature_write_addr_gen_Add_32Ux32U_32U_1_16_out1 );

  SC_METHOD(feature_write_addr_gen_N_MuxB_320_2_4_4_40);
  sensitive << ( feature_write_addr_gen_Or_1Ux1U_1U_4_35_out1 );
  sensitive << ( fifo_out );

  SC_METHOD(feature_write_addr_gen_N_MuxB_320_2_5_4_41);
  sensitive << ( read_address_valid );
  sensitive << ( data_in );

  SC_METHOD(feature_write_addr_gen_And_1Ux1U_1U_4_42);
  sensitive << ( feature_write_addr_gen_OrReduction_3U_1U_4_36_out1 );
  sensitive << ( feature_write_addr_gen_Not_1U_1U_4_37_out1 );

  SC_METHOD(feature_write_addr_gen_Or_1Ux1U_1U_4_43);
  sensitive << ( read_address_valid );
  sensitive << ( feature_write_addr_gen_OrReduction_3U_1U_4_36_out1 );

  SC_METHOD(feature_write_addr_gen_N_Mux_32_2_2_4_44);
  sensitive << ( read_address_valid );
  sensitive << ( read_address );
  sensitive << ( feature_write_addr_gen_N_Mux_32_2_6_4_39_out1 );

  SC_METHOD(feature_write_addr_gen_Not_1U_1U_1_17);
  sensitive << ( read_address_valid );

  SC_METHOD(drive_fifo_cnt_1d);
  sensitive << clk.pos();
  sensitive << rstn.neg();
  dont_initialize();

}
// resource: regr_ac_3
void feature_write_addr_gen::drive_rd_ptr(){
  if ( (rstn.read() == 0ULL) ) {
    rd_ptr = 0ULL;
  } else {
    rd_ptr = feature_write_addr_gen_N_Mux_3_2_0_4_29_out1.read();
  }
}
// resource: feature_write_addr_gen_OrReduction_3U_1U_4  instance: feature_write_addr_gen_OrReduction_3U_1U_4_26
void feature_write_addr_gen::feature_write_addr_gen_OrReduction_3U_1U_4_26(){
  feature_write_addr_gen_OrReduction_3U_1U_4_26_out1 = (sc_uint<1> ) (
                                                       ((sc_uint<3>)fifo_cnt
                                                       .read()).or_reduce());
}
// resource: feature_write_addr_gen_And_1Ux1U_1U_4  instance: feature_write_addr_gen_And_1Ux1U_1U_4_27
void feature_write_addr_gen::feature_write_addr_gen_And_1Ux1U_1U_4_27(){
  feature_write_addr_gen_And_1Ux1U_1U_4_27_out1 = feature_write_addr_gen_And_1Ux1U_1U_1_25_out1
                                                  .read() & feature_write_addr_gen_OrReduction_3U_1U_4_26_out1
                                                  .read();
}
// resource: feature_write_addr_gen_Add_3Ux1U_3U_4  instance: feature_write_addr_gen_Add_3Ux1U_3U_4_28
void feature_write_addr_gen::feature_write_addr_gen_Add_3Ux1U_3U_4_28(){
  feature_write_addr_gen_Add_3Ux1U_3U_4_28_out1 = (rd_ptr.read() + 1ULL);
}
// resource: feature_write_addr_gen_N_Mux_3_2_0_4
void feature_write_addr_gen::feature_write_addr_gen_N_Mux_3_2_0_4_29(){
  if ( feature_write_addr_gen_And_1Ux1U_1U_4_27_out1.read() ) {
    feature_write_addr_gen_N_Mux_3_2_0_4_29_out1 = feature_write_addr_gen_Add_3Ux1U_3U_4_28_out1
                                                   .read();
  } else {
    feature_write_addr_gen_N_Mux_3_2_0_4_29_out1 = rd_ptr.read();
  }
}
// resource: regr_ac_3
void feature_write_addr_gen::drive_wr_ptr(){
  if ( (rstn.read() == 0ULL) ) {
    wr_ptr = 0ULL;
  } else {
    wr_ptr = feature_write_addr_gen_N_Mux_3_2_0_4_4_out1.read();
  }
}
// resource: feature_write_addr_gen_NotEQ_3Ux3U_1U_4  instance: feature_write_addr_gen_NotEQ_3Ux3U_1U_4_1
void feature_write_addr_gen::feature_write_addr_gen_NotEQ_3Ux3U_1U_4_1(){
  feature_write_addr_gen_NotEQ_3Ux3U_1U_4_1_out1 = (fifo_cnt.read() != 7ULL);
}
// resource: feature_write_addr_gen_And_1Ux1U_1U_4  instance: feature_write_addr_gen_And_1Ux1U_1U_4_2
void feature_write_addr_gen::feature_write_addr_gen_And_1Ux1U_1U_4_2(){
  feature_write_addr_gen_And_1Ux1U_1U_4_2_out1 = feature_write_addr_gen_NotEQ_3Ux3U_1U_4_1_out1
                                                 .read() & (sc_uint<1> )src_vld
                                                 .read();
}
// resource: feature_write_addr_gen_Add_3Ux1U_3U_4  instance: feature_write_addr_gen_Add_3Ux1U_3U_4_3
void feature_write_addr_gen::feature_write_addr_gen_Add_3Ux1U_3U_4_3(){
  feature_write_addr_gen_Add_3Ux1U_3U_4_3_out1 = (wr_ptr.read() + 1ULL);
}
// resource: feature_write_addr_gen_N_Mux_3_2_0_4
void feature_write_addr_gen::feature_write_addr_gen_N_Mux_3_2_0_4_4(){
  if ( feature_write_addr_gen_And_1Ux1U_1U_4_2_out1.read() ) {
    feature_write_addr_gen_N_Mux_3_2_0_4_4_out1 = feature_write_addr_gen_Add_3Ux1U_3U_4_3_out1
                                                  .read();
  } else {
    feature_write_addr_gen_N_Mux_3_2_0_4_4_out1 = wr_ptr.read();
  }
}
// resource: feature_write_addr_gen_OrReduction_3U_1U_1  instance: feature_write_addr_gen_OrReduction_3U_1U_1_24
void feature_write_addr_gen::feature_write_addr_gen_OrReduction_3U_1U_1_24(){
  feature_write_addr_gen_OrReduction_3U_1U_1_24_out1 = (sc_uint<1> ) (
                                                       ((sc_uint<3>)fifo_cnt
                                                       .read()).or_reduce());
}
// resource: feature_write_addr_gen_And_1Ux1U_1U_1  instance: feature_write_addr_gen_And_1Ux1U_1U_1_25
void feature_write_addr_gen::feature_write_addr_gen_And_1Ux1U_1U_1_25(){
  feature_write_addr_gen_And_1Ux1U_1U_1_25_out1 = feature_write_addr_gen_OrReduction_3U_1U_1_24_out1
                                                  .read() & feature_write_addr_gen_Not_1U_1U_1_17_out1
                                                  .read();
}
// resource: regr_ac_3
void feature_write_addr_gen::drive_fifo_cnt(){
  if ( (rstn.read() == 0ULL) ) {
    fifo_cnt = 0ULL;
  } else {
    fifo_cnt = feature_write_addr_gen_N_Mux_3_2_0_4_23_out1.read();
  }
}
// resource: feature_write_addr_gen_OrReduction_3U_1U_4  instance: feature_write_addr_gen_OrReduction_3U_1U_4_18
void feature_write_addr_gen::feature_write_addr_gen_OrReduction_3U_1U_4_18(){
  feature_write_addr_gen_OrReduction_3U_1U_4_18_out1 = (sc_uint<1> ) (
                                                       ((sc_uint<3>)fifo_cnt
                                                       .read()).or_reduce());
}
// resource: feature_write_addr_gen_And_1Ux1U_1U_4  instance: feature_write_addr_gen_And_1Ux1U_1U_4_19
void feature_write_addr_gen::feature_write_addr_gen_And_1Ux1U_1U_4_19(){
  feature_write_addr_gen_And_1Ux1U_1U_4_19_out1 = feature_write_addr_gen_OrReduction_3U_1U_4_18_out1
                                                  .read() & feature_write_addr_gen_Not_1U_1U_1_17_out1
                                                  .read();
}
// resource: feature_write_addr_gen_Sub_3Ux1U_3S_4  instance: feature_write_addr_gen_Sub_3Ux1U_3S_4_20
void feature_write_addr_gen::feature_write_addr_gen_Sub_3Ux1U_3S_4_20(){
  feature_write_addr_gen_Sub_3Ux1U_3S_4_20_out1 = fifo_cnt.read() - 1ULL;
}
// resource: feature_write_addr_gen_Add_3Ux1U_3U_4  instance: feature_write_addr_gen_Add_3Ux1U_3U_4_21
void feature_write_addr_gen::feature_write_addr_gen_Add_3Ux1U_3U_4_21(){
  feature_write_addr_gen_Add_3Ux1U_3U_4_21_out1 = (fifo_cnt.read() + 1ULL);
}
// resource: feature_write_addr_gen_N_Mux_3_2_0_4
void feature_write_addr_gen::feature_write_addr_gen_N_Mux_3_2_0_4_22(){
  if ( feature_write_addr_gen_And_1Ux1U_1U_4_19_out1.read() ) {
    feature_write_addr_gen_N_Mux_3_2_0_4_22_out1 = (sc_uint<3> ) (feature_write_addr_gen_Sub_3Ux1U_3S_4_20_out1
                                                   .read());
  } else {
    feature_write_addr_gen_N_Mux_3_2_0_4_22_out1 = fifo_cnt.read();
  }
}
// resource: feature_write_addr_gen_N_Mux_3_2_0_4
void feature_write_addr_gen::feature_write_addr_gen_N_Mux_3_2_0_4_23(){
  if ( src_vld.read() ) {
    feature_write_addr_gen_N_Mux_3_2_0_4_23_out1 = feature_write_addr_gen_Add_3Ux1U_3U_4_21_out1
                                                   .read();
  } else {
    feature_write_addr_gen_N_Mux_3_2_0_4_23_out1 = feature_write_addr_gen_N_Mux_3_2_0_4_22_out1
                                                   .read();
  }
}
// resource: mux_320bx2i1c
void feature_write_addr_gen::drive_fifo_out(){
  if ( feature_write_addr_gen_And_1Ux1U_1U_4_31_out1.read() ) {
    fifo_out = feature_write_addr_gen_N_MuxB_320_8_1_1_32_out1.read();
  } else {
    fifo_out = sc_biguint<320>(0ULL);
  }
}
// resource: feature_write_addr_gen_OrReduction_3U_1U_4  instance: feature_write_addr_gen_OrReduction_3U_1U_4_30
void feature_write_addr_gen::feature_write_addr_gen_OrReduction_3U_1U_4_30(){
  feature_write_addr_gen_OrReduction_3U_1U_4_30_out1 = (sc_uint<1> ) (
                                                       ((sc_uint<3>)fifo_cnt
                                                       .read()).or_reduce());
}
// resource: feature_write_addr_gen_And_1Ux1U_1U_4  instance: feature_write_addr_gen_And_1Ux1U_1U_4_31
void feature_write_addr_gen::feature_write_addr_gen_And_1Ux1U_1U_4_31(){
  feature_write_addr_gen_And_1Ux1U_1U_4_31_out1 = feature_write_addr_gen_And_1Ux1U_1U_1_25_out1
                                                  .read() & feature_write_addr_gen_OrReduction_3U_1U_4_30_out1
                                                  .read();
}
// resource: feature_write_addr_gen_N_MuxB_320_8_1_1
void feature_write_addr_gen::feature_write_addr_gen_N_MuxB_320_8_1_1_32(){
  switch( (sc_uint<3>)(rd_ptr.read()) ) {
  default:
    feature_write_addr_gen_N_MuxB_320_8_1_1_32_out1 = fifo_mem_7.read();
    break;
  case 0ULL: 
    feature_write_addr_gen_N_MuxB_320_8_1_1_32_out1 = fifo_mem_0.read();
    break;
  case 1ULL: 
    feature_write_addr_gen_N_MuxB_320_8_1_1_32_out1 = fifo_mem_1.read();
    break;
  case 2ULL: 
    feature_write_addr_gen_N_MuxB_320_8_1_1_32_out1 = fifo_mem_2.read();
    break;
  case 3ULL: 
    feature_write_addr_gen_N_MuxB_320_8_1_1_32_out1 = fifo_mem_3.read();
    break;
  case 4ULL: 
    feature_write_addr_gen_N_MuxB_320_8_1_1_32_out1 = fifo_mem_4.read();
    break;
  case 5ULL: 
    feature_write_addr_gen_N_MuxB_320_8_1_1_32_out1 = fifo_mem_5.read();
    break;
  case 6ULL: 
    feature_write_addr_gen_N_MuxB_320_8_1_1_32_out1 = fifo_mem_6.read();
    break;
  }
}
// resource: regr_en_ac_320
void feature_write_addr_gen::drive_fifo_mem_0(){
  if ( (rstn.read() == 0ULL) ) {
    fifo_mem_0 = sc_biguint<320>(0ULL);
  } else {
    switch( (sc_uint<1>)(feature_write_addr_gen_And_1Ux1U_1U_4_6_out1.read() & 
            feature_write_addr_gen_Not_1U_1U_4_15_out1.read()) ) {
    case 1ULL: 
      fifo_mem_0 = src.read();
      break;
    case 0ULL: 
      break;
    }
  }
}
// resource: regr_en_ac_320
void feature_write_addr_gen::drive_fifo_mem_1(){
  if ( (rstn.read() == 0ULL) ) {
    fifo_mem_1 = sc_biguint<320>(0ULL);
  } else {
    switch( (sc_uint<1>)(feature_write_addr_gen_And_1Ux1U_1U_4_6_out1.read() & 
            feature_write_addr_gen_Equal_3Ux1U_1U_4_14_out1.read()) ) {
    case 1ULL: 
      fifo_mem_1 = src.read();
      break;
    case 0ULL: 
      break;
    }
  }
}
// resource: regr_en_ac_320
void feature_write_addr_gen::drive_fifo_mem_2(){
  if ( (rstn.read() == 0ULL) ) {
    fifo_mem_2 = sc_biguint<320>(0ULL);
  } else {
    switch( (sc_uint<1>)(feature_write_addr_gen_And_1Ux1U_1U_4_6_out1.read() & 
            feature_write_addr_gen_Equal_3Ux2U_1U_4_13_out1.read()) ) {
    case 1ULL: 
      fifo_mem_2 = src.read();
      break;
    case 0ULL: 
      break;
    }
  }
}
// resource: regr_en_ac_320
void feature_write_addr_gen::drive_fifo_mem_3(){
  if ( (rstn.read() == 0ULL) ) {
    fifo_mem_3 = sc_biguint<320>(0ULL);
  } else {
    switch( (sc_uint<1>)(feature_write_addr_gen_And_1Ux1U_1U_4_6_out1.read() & 
            feature_write_addr_gen_Equal_3Ux2U_1U_4_12_out1.read()) ) {
    case 1ULL: 
      fifo_mem_3 = src.read();
      break;
    case 0ULL: 
      break;
    }
  }
}
// resource: regr_en_ac_320
void feature_write_addr_gen::drive_fifo_mem_4(){
  if ( (rstn.read() == 0ULL) ) {
    fifo_mem_4 = sc_biguint<320>(0ULL);
  } else {
    switch( (sc_uint<1>)(feature_write_addr_gen_And_1Ux1U_1U_4_6_out1.read() & 
            feature_write_addr_gen_Equal_3Ux3U_1U_4_11_out1.read()) ) {
    case 1ULL: 
      fifo_mem_4 = src.read();
      break;
    case 0ULL: 
      break;
    }
  }
}
// resource: regr_en_ac_320
void feature_write_addr_gen::drive_fifo_mem_5(){
  if ( (rstn.read() == 0ULL) ) {
    fifo_mem_5 = sc_biguint<320>(0ULL);
  } else {
    switch( (sc_uint<1>)(feature_write_addr_gen_And_1Ux1U_1U_4_6_out1.read() & 
            feature_write_addr_gen_Equal_3Ux3U_1U_4_10_out1.read()) ) {
    case 1ULL: 
      fifo_mem_5 = src.read();
      break;
    case 0ULL: 
      break;
    }
  }
}
// resource: regr_en_ac_320
void feature_write_addr_gen::drive_fifo_mem_6(){
  if ( (rstn.read() == 0ULL) ) {
    fifo_mem_6 = sc_biguint<320>(0ULL);
  } else {
    switch( (sc_uint<1>)(feature_write_addr_gen_And_1Ux1U_1U_4_6_out1.read() & 
            feature_write_addr_gen_Equal_3Ux3U_1U_4_9_out1.read()) ) {
    case 1ULL: 
      fifo_mem_6 = src.read();
      break;
    case 0ULL: 
      break;
    }
  }
}
// resource: regr_en_ac_320
void feature_write_addr_gen::drive_fifo_mem_7(){
  if ( (rstn.read() == 0ULL) ) {
    fifo_mem_7 = sc_biguint<320>(0ULL);
  } else {
    switch( (sc_uint<1>)(feature_write_addr_gen_And_1Ux1U_1U_4_6_out1.read() & 
            feature_write_addr_gen_Equal_3Ux3U_1U_4_8_out1.read()) ) {
    case 1ULL: 
      fifo_mem_7 = src.read();
      break;
    case 0ULL: 
      break;
    }
  }
}
// resource: feature_write_addr_gen_NotEQ_3Ux3U_1U_4  instance: feature_write_addr_gen_NotEQ_3Ux3U_1U_4_5
void feature_write_addr_gen::feature_write_addr_gen_NotEQ_3Ux3U_1U_4_5(){
  feature_write_addr_gen_NotEQ_3Ux3U_1U_4_5_out1 = (fifo_cnt.read() != 7ULL);
}
// resource: feature_write_addr_gen_And_1Ux1U_1U_4  instance: feature_write_addr_gen_And_1Ux1U_1U_4_6
void feature_write_addr_gen::feature_write_addr_gen_And_1Ux1U_1U_4_6(){
  feature_write_addr_gen_And_1Ux1U_1U_4_6_out1 = feature_write_addr_gen_NotEQ_3Ux3U_1U_4_5_out1
                                                 .read() & (sc_uint<1> )src_vld
                                                 .read();
}
// resource: feature_write_addr_gen_OrReduction_3U_1U_4  instance: feature_write_addr_gen_OrReduction_3U_1U_4_7
void feature_write_addr_gen::feature_write_addr_gen_OrReduction_3U_1U_4_7(){
  feature_write_addr_gen_OrReduction_3U_1U_4_7_out1 = (sc_uint<1> ) (
                                                      ((sc_uint<3>)wr_ptr.read()
                                                      ).or_reduce());
}
// resource: feature_write_addr_gen_Equal_3Ux3U_1U_4  instance: feature_write_addr_gen_Equal_3Ux3U_1U_4_8
void feature_write_addr_gen::feature_write_addr_gen_Equal_3Ux3U_1U_4_8(){
  feature_write_addr_gen_Equal_3Ux3U_1U_4_8_out1 = (wr_ptr.read() == 7ULL);
}
// resource: feature_write_addr_gen_Equal_3Ux3U_1U_4  instance: feature_write_addr_gen_Equal_3Ux3U_1U_4_9
void feature_write_addr_gen::feature_write_addr_gen_Equal_3Ux3U_1U_4_9(){
  feature_write_addr_gen_Equal_3Ux3U_1U_4_9_out1 = (wr_ptr.read() == 6ULL);
}
// resource: feature_write_addr_gen_Equal_3Ux3U_1U_4  instance: feature_write_addr_gen_Equal_3Ux3U_1U_4_10
void feature_write_addr_gen::feature_write_addr_gen_Equal_3Ux3U_1U_4_10(){
  feature_write_addr_gen_Equal_3Ux3U_1U_4_10_out1 = (wr_ptr.read() == 5ULL);
}
// resource: feature_write_addr_gen_Equal_3Ux3U_1U_4  instance: feature_write_addr_gen_Equal_3Ux3U_1U_4_11
void feature_write_addr_gen::feature_write_addr_gen_Equal_3Ux3U_1U_4_11(){
  feature_write_addr_gen_Equal_3Ux3U_1U_4_11_out1 = (wr_ptr.read() == 4ULL);
}
// resource: feature_write_addr_gen_Equal_3Ux2U_1U_4  instance: feature_write_addr_gen_Equal_3Ux2U_1U_4_12
void feature_write_addr_gen::feature_write_addr_gen_Equal_3Ux2U_1U_4_12(){
  feature_write_addr_gen_Equal_3Ux2U_1U_4_12_out1 = (wr_ptr.read() == 3ULL);
}
// resource: feature_write_addr_gen_Equal_3Ux2U_1U_4  instance: feature_write_addr_gen_Equal_3Ux2U_1U_4_13
void feature_write_addr_gen::feature_write_addr_gen_Equal_3Ux2U_1U_4_13(){
  feature_write_addr_gen_Equal_3Ux2U_1U_4_13_out1 = (wr_ptr.read() == 2ULL);
}
// resource: feature_write_addr_gen_Equal_3Ux1U_1U_4  instance: feature_write_addr_gen_Equal_3Ux1U_1U_4_14
void feature_write_addr_gen::feature_write_addr_gen_Equal_3Ux1U_1U_4_14(){
  feature_write_addr_gen_Equal_3Ux1U_1U_4_14_out1 = (wr_ptr.read() == 1ULL);
}
// resource: feature_write_addr_gen_Not_1U_1U_4  instance: feature_write_addr_gen_Not_1U_1U_4_15
void feature_write_addr_gen::feature_write_addr_gen_Not_1U_1U_4_15(){
  feature_write_addr_gen_Not_1U_1U_4_15_out1 = !feature_write_addr_gen_OrReduction_3U_1U_4_7_out1
                                               .read();
}
// resource: regr_ac_32
void feature_write_addr_gen::drive_write_cnt(){
  if ( (rstn.read() == 0ULL) ) {
    write_cnt = 0ULL;
  } else {
    write_cnt = feature_write_addr_gen_N_Mux_32_2_3_4_47_out1.read();
  }
}
// resource: feature_write_addr_gen_Add_32Ux1U_32U_4  instance: feature_write_addr_gen_Add_32Ux1U_32U_4_45
void feature_write_addr_gen::feature_write_addr_gen_Add_32Ux1U_32U_4_45(){
  feature_write_addr_gen_Add_32Ux1U_32U_4_45_out1 = (/*cliff*/sc_uint<32>)(
                                                    write_cnt.read() + 1ULL);
}
// resource: feature_write_addr_gen_N_Mux_32_2_2_4
void feature_write_addr_gen::feature_write_addr_gen_N_Mux_32_2_2_4_46(){
  if ( we_0.read() ) {
    feature_write_addr_gen_N_Mux_32_2_2_4_46_out1 = feature_write_addr_gen_Add_32Ux1U_32U_4_45_out1
                                                    .read();
  } else {
    feature_write_addr_gen_N_Mux_32_2_2_4_46_out1 = write_cnt.read();
  }
}
// resource: feature_write_addr_gen_N_Mux_32_2_3_4
void feature_write_addr_gen::feature_write_addr_gen_N_Mux_32_2_3_4_47(){
  if ( init.read() ) {
    feature_write_addr_gen_N_Mux_32_2_3_4_47_out1 = 0ULL;
  } else {
    feature_write_addr_gen_N_Mux_32_2_3_4_47_out1 = feature_write_addr_gen_N_Mux_32_2_2_4_46_out1
                                                    .read();
  }
}
// resource: feature_write_addr_gen_Add_32Ux32U_32U_1  instance: feature_write_addr_gen_Add_32Ux32U_32U_1_16
void feature_write_addr_gen::feature_write_addr_gen_Add_32Ux32U_32U_1_16(){
  feature_write_addr_gen_Add_32Ux32U_32U_1_16_out1 = (write_cnt.read() + 
                                                     base_addr.read());
}
void feature_write_addr_gen::drive_stop(){
  stop = src_vld.read();
}
void feature_write_addr_gen::drive_data_out(){
  data_out = feature_write_addr_gen_N_MuxB_320_2_4_4_40_out1.read();
}
void feature_write_addr_gen::drive_oe_0(){
  oe_0 = read_address_valid.read();
}
void feature_write_addr_gen::drive_we_0(){
  we_0 = (sc_uint<1> ) (feature_write_addr_gen_And_1Ux1U_1U_4_42_out1.read());
}
void feature_write_addr_gen::drive_cs_0(){
  cs_0 = (sc_uint<1> ) (feature_write_addr_gen_Or_1Ux1U_1U_4_43_out1.read());
}
void feature_write_addr_gen::drive_address_0(){
  address_0 = (sc_uint<32> ) (feature_write_addr_gen_N_Mux_32_2_2_4_44_out1
              .read());
}
void feature_write_addr_gen::drive_read_data(){
  read_data = feature_write_addr_gen_N_MuxB_320_2_5_4_41_out1.read();
}
// resource: feature_write_addr_gen_OrReduction_3U_1U_4  instance: feature_write_addr_gen_OrReduction_3U_1U_4_36
void feature_write_addr_gen::feature_write_addr_gen_OrReduction_3U_1U_4_36(){
  feature_write_addr_gen_OrReduction_3U_1U_4_36_out1 = (sc_uint<1> ) (
                                                       ((sc_uint<3>)fifo_cnt_1d
                                                       .read()).or_reduce());
}
// resource: feature_write_addr_gen_Not_1U_1U_4  instance: feature_write_addr_gen_Not_1U_1U_4_34
void feature_write_addr_gen::feature_write_addr_gen_Not_1U_1U_4_34(){
  feature_write_addr_gen_Not_1U_1U_4_34_out1 = !feature_write_addr_gen_OrReduction_3U_1U_4_36_out1
                                               .read();
}
// resource: feature_write_addr_gen_Or_1Ux1U_1U_4  instance: feature_write_addr_gen_Or_1Ux1U_1U_4_35
void feature_write_addr_gen::feature_write_addr_gen_Or_1Ux1U_1U_4_35(){
  feature_write_addr_gen_Or_1Ux1U_1U_4_35_out1 = feature_write_addr_gen_Not_1U_1U_4_34_out1
                                                 .read() | (sc_uint<1> )
                                                 read_address_valid.read();
}
// resource: feature_write_addr_gen_Not_1U_1U_4  instance: feature_write_addr_gen_Not_1U_1U_4_37
void feature_write_addr_gen::feature_write_addr_gen_Not_1U_1U_4_37(){
  feature_write_addr_gen_Not_1U_1U_4_37_out1 = !read_address_valid.read();
}
// resource: feature_write_addr_gen_N_Mux_32_2_6_4
void feature_write_addr_gen::feature_write_addr_gen_N_Mux_32_2_6_4_39(){
  if ( feature_write_addr_gen_OrReduction_3U_1U_4_36_out1.read() ) {
    feature_write_addr_gen_N_Mux_32_2_6_4_39_out1 = feature_write_addr_gen_Add_32Ux32U_32U_1_16_out1
                                                    .read();
  } else {
    feature_write_addr_gen_N_Mux_32_2_6_4_39_out1 = 0ULL;
  }
}
// resource: feature_write_addr_gen_N_MuxB_320_2_4_4
void feature_write_addr_gen::feature_write_addr_gen_N_MuxB_320_2_4_4_40(){
  if ( feature_write_addr_gen_Or_1Ux1U_1U_4_35_out1.read() ) {
    feature_write_addr_gen_N_MuxB_320_2_4_4_40_out1 = sc_biguint<320>(0ULL);
  } else {
    feature_write_addr_gen_N_MuxB_320_2_4_4_40_out1 = fifo_out.read();
  }
}
// resource: feature_write_addr_gen_N_MuxB_320_2_5_4
void feature_write_addr_gen::feature_write_addr_gen_N_MuxB_320_2_5_4_41(){
  if ( read_address_valid.read() ) {
    feature_write_addr_gen_N_MuxB_320_2_5_4_41_out1 = data_in.read();
  } else {
    feature_write_addr_gen_N_MuxB_320_2_5_4_41_out1 = sc_biguint<320>(0ULL);
  }
}
// resource: feature_write_addr_gen_And_1Ux1U_1U_4  instance: feature_write_addr_gen_And_1Ux1U_1U_4_42
void feature_write_addr_gen::feature_write_addr_gen_And_1Ux1U_1U_4_42(){
  feature_write_addr_gen_And_1Ux1U_1U_4_42_out1 = feature_write_addr_gen_Not_1U_1U_4_37_out1
                                                  .read() & feature_write_addr_gen_OrReduction_3U_1U_4_36_out1
                                                  .read();
}
// resource: feature_write_addr_gen_Or_1Ux1U_1U_4  instance: feature_write_addr_gen_Or_1Ux1U_1U_4_43
void feature_write_addr_gen::feature_write_addr_gen_Or_1Ux1U_1U_4_43(){
  feature_write_addr_gen_Or_1Ux1U_1U_4_43_out1 = feature_write_addr_gen_OrReduction_3U_1U_4_36_out1
                                                 .read() | (sc_uint<1> )
                                                 read_address_valid.read();
}
// resource: feature_write_addr_gen_N_Mux_32_2_2_4
void feature_write_addr_gen::feature_write_addr_gen_N_Mux_32_2_2_4_44(){
  if ( read_address_valid.read() ) {
    feature_write_addr_gen_N_Mux_32_2_2_4_44_out1 = (sc_uint<32> ) (read_address
                                                    .read());
  } else {
    feature_write_addr_gen_N_Mux_32_2_2_4_44_out1 = (sc_uint<32> ) (feature_write_addr_gen_N_Mux_32_2_6_4_39_out1
                                                    .read());
  }
}
// resource: feature_write_addr_gen_Not_1U_1U_1  instance: feature_write_addr_gen_Not_1U_1U_1_17
void feature_write_addr_gen::feature_write_addr_gen_Not_1U_1U_1_17(){
  feature_write_addr_gen_Not_1U_1U_1_17_out1 = !read_address_valid.read();
}
// resource: regr_ac_3
void feature_write_addr_gen::drive_fifo_cnt_1d(){
  if ( (rstn.read() == 0ULL) ) {
    fifo_cnt_1d = 0ULL;
  } else {
    fifo_cnt_1d = fifo_cnt.read();
  }
}
