`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Dec  7 2020 22:19:36 KST (Dec  7 2020 13:19:36 UTC)

module st_feature_addr_gen_EqSubi1u11u16_1(in2, in1, out1);
  input [15:0] in2;
  input [10:0] in1;
  output out1;
  wire [15:0] in2;
  wire [10:0] in1;
  wire out1;
  wire dec_sub_24_2_n_2, dec_sub_24_2_n_3, dec_sub_24_2_n_6,
       dec_sub_24_2_n_7, dec_sub_24_2_n_8, dec_sub_24_2_n_9,
       dec_sub_24_2_n_10, dec_sub_24_2_n_11;
  wire dec_sub_24_2_n_12, dec_sub_24_2_n_13, dec_sub_24_2_n_14,
       dec_sub_24_2_n_15, dec_sub_24_2_n_16, dec_sub_24_2_n_17,
       dec_sub_24_2_n_18, dec_sub_24_2_n_19;
  wire dec_sub_24_2_n_20, dec_sub_24_2_n_21, dec_sub_24_2_n_22,
       dec_sub_24_2_n_23, dec_sub_24_2_n_24, dec_sub_24_2_n_25,
       dec_sub_24_2_n_28, dec_sub_24_2_n_29;
  wire dec_sub_24_2_n_30, dec_sub_24_2_n_33, dec_sub_24_2_n_36,
       dec_sub_24_2_n_37, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  NOR3BX1 g183(.AN (n_32), .B (n_31), .C (n_29), .Y (out1));
  NOR2BXL g184(.AN (n_14), .B (n_30), .Y (n_32));
  NAND2X1 g185(.A (n_23), .B (n_27), .Y (n_31));
  NAND2XL g186(.A (n_8), .B (n_28), .Y (n_30));
  NAND3X1 g187(.A (n_25), .B (n_21), .C (n_19), .Y (n_29));
  NOR3BX1 g188(.AN (n_18), .B (n_26), .C (n_0), .Y (n_28));
  NOR2X1 g189(.A (n_22), .B (n_24), .Y (n_27));
  NAND2X1 g190(.A (n_15), .B (n_17), .Y (n_26));
  AOI21X1 g191(.A0 (n_7), .A1 (n_6), .B0 (n_9), .Y (n_25));
  NAND2X1 g192(.A (n_11), .B (n_10), .Y (n_24));
  AND2XL g193(.A (n_16), .B (n_20), .Y (n_23));
  NAND2X1 g194(.A (n_13), .B (n_12), .Y (n_22));
  XNOR2X1 g195(.A (in2[8]), .B (n_40), .Y (n_21));
  XNOR2X1 g197(.A (in2[4]), .B (n_36), .Y (n_20));
  MXI2XL g198(.A (in2[9]), .B (n_5), .S0 (n_41), .Y (n_19));
  MXI2XL g199(.A (in2[2]), .B (n_3), .S0 (n_34), .Y (n_18));
  XNOR2X1 g200(.A (in2[1]), .B (n_33), .Y (n_17));
  MXI2XL g201(.A (in2[6]), .B (n_2), .S0 (n_38), .Y (n_16));
  XOR2XL g202(.A (in2[0]), .B (in1[0]), .Y (n_15));
  MXI2XL g203(.A (in2[10]), .B (n_1), .S0 (n_42), .Y (n_14));
  XNOR2X1 g204(.A (in2[14]), .B (n_43), .Y (n_13));
  XNOR2X1 g205(.A (in2[13]), .B (n_43), .Y (n_12));
  XNOR2X1 g206(.A (in2[12]), .B (n_43), .Y (n_11));
  XNOR2X1 g207(.A (in2[11]), .B (n_43), .Y (n_10));
  MXI2XL g208(.A (n_4), .B (in2[7]), .S0 (n_39), .Y (n_9));
  NOR2XL g209(.A (in2[15]), .B (n_43), .Y (n_8));
  NAND2X1 g210(.A (in2[5]), .B (n_37), .Y (n_7));
  OR2XL g211(.A (in2[5]), .B (n_37), .Y (n_6));
  INVX1 g212(.A (in2[9]), .Y (n_5));
  INVXL g213(.A (in2[7]), .Y (n_4));
  INVX1 g214(.A (in2[2]), .Y (n_3));
  INVX1 g216(.A (in2[6]), .Y (n_2));
  INVX1 g217(.A (in2[10]), .Y (n_1));
  XOR2XL g2(.A (in2[3]), .B (n_35), .Y (n_0));
  NAND2BXL dec_sub_24_2_g127(.AN (dec_sub_24_2_n_36), .B
       (dec_sub_24_2_n_37), .Y (n_41));
  NAND2XL dec_sub_24_2_g128(.A (in1[9]), .B (dec_sub_24_2_n_29), .Y
       (dec_sub_24_2_n_37));
  NOR3XL dec_sub_24_2_g129(.A (in1[9]), .B (in1[8]), .C
       (dec_sub_24_2_n_22), .Y (dec_sub_24_2_n_36));
  MXI2XL dec_sub_24_2_g130(.A (dec_sub_24_2_n_7), .B (in1[5]), .S0
       (dec_sub_24_2_n_24), .Y (n_37));
  NAND2BX1 dec_sub_24_2_g131(.AN (dec_sub_24_2_n_2), .B
       (dec_sub_24_2_n_33), .Y (n_42));
  NAND2XL dec_sub_24_2_g133(.A (in1[10]), .B (dec_sub_24_2_n_30), .Y
       (dec_sub_24_2_n_33));
  MXI2XL dec_sub_24_2_g136(.A (dec_sub_24_2_n_8), .B (in1[6]), .S0
       (dec_sub_24_2_n_25), .Y (n_38));
  MXI2X1 dec_sub_24_2_g137(.A (dec_sub_24_2_n_6), .B (in1[7]), .S0
       (dec_sub_24_2_n_20), .Y (n_39));
  NAND2X1 dec_sub_24_2_g138(.A (dec_sub_24_2_n_13), .B
       (dec_sub_24_2_n_21), .Y (dec_sub_24_2_n_30));
  NAND2BX1 dec_sub_24_2_g140(.AN (in1[8]), .B (dec_sub_24_2_n_21), .Y
       (dec_sub_24_2_n_29));
  NAND2XL dec_sub_24_2_g141(.A (in1[8]), .B (dec_sub_24_2_n_22), .Y
       (dec_sub_24_2_n_28));
  NAND2BXL dec_sub_24_2_g142(.AN (dec_sub_24_2_n_24), .B
       (dec_sub_24_2_n_23), .Y (n_36));
  NOR2X2 dec_sub_24_2_g143(.A (dec_sub_24_2_n_15), .B
       (dec_sub_24_2_n_22), .Y (n_43));
  NOR2BX1 dec_sub_24_2_g144(.AN (dec_sub_24_2_n_10), .B
       (dec_sub_24_2_n_18), .Y (dec_sub_24_2_n_25));
  NOR2X1 dec_sub_24_2_g145(.A (in1[4]), .B (dec_sub_24_2_n_18), .Y
       (dec_sub_24_2_n_24));
  NAND2XL dec_sub_24_2_g146(.A (in1[4]), .B (dec_sub_24_2_n_18), .Y
       (dec_sub_24_2_n_23));
  INVX1 dec_sub_24_2_g147(.A (dec_sub_24_2_n_22), .Y
       (dec_sub_24_2_n_21));
  NAND2X4 dec_sub_24_2_g148(.A (dec_sub_24_2_n_17), .B
       (dec_sub_24_2_n_14), .Y (dec_sub_24_2_n_22));
  NOR2X1 dec_sub_24_2_g150(.A (dec_sub_24_2_n_16), .B
       (dec_sub_24_2_n_18), .Y (dec_sub_24_2_n_20));
  NOR2BX1 dec_sub_24_2_g153(.AN (in1[2]), .B (dec_sub_24_2_n_11), .Y
       (dec_sub_24_2_n_19));
  CLKINVX2 dec_sub_24_2_g154(.A (dec_sub_24_2_n_17), .Y
       (dec_sub_24_2_n_18));
  CLKAND2X3 dec_sub_24_2_g155(.A (dec_sub_24_2_n_9), .B
       (dec_sub_24_2_n_11), .Y (dec_sub_24_2_n_17));
  NAND2X1 dec_sub_24_2_g157(.A (dec_sub_24_2_n_8), .B
       (dec_sub_24_2_n_10), .Y (dec_sub_24_2_n_16));
  NAND2BX1 dec_sub_24_2_g158(.AN (in1[10]), .B (dec_sub_24_2_n_13), .Y
       (dec_sub_24_2_n_15));
  CLKAND2X2 dec_sub_24_2_g159(.A (dec_sub_24_2_n_12), .B
       (dec_sub_24_2_n_10), .Y (dec_sub_24_2_n_14));
  NOR2X1 dec_sub_24_2_g162(.A (in1[9]), .B (in1[8]), .Y
       (dec_sub_24_2_n_13));
  NOR2X1 dec_sub_24_2_g163(.A (in1[7]), .B (in1[6]), .Y
       (dec_sub_24_2_n_12));
  NOR2X6 dec_sub_24_2_g164(.A (in1[1]), .B (in1[0]), .Y
       (dec_sub_24_2_n_11));
  NOR2X1 dec_sub_24_2_g165(.A (in1[5]), .B (in1[4]), .Y
       (dec_sub_24_2_n_10));
  NOR2X2 dec_sub_24_2_g166(.A (in1[3]), .B (in1[2]), .Y
       (dec_sub_24_2_n_9));
  INVX1 dec_sub_24_2_g168(.A (in1[6]), .Y (dec_sub_24_2_n_8));
  INVX1 dec_sub_24_2_g169(.A (in1[5]), .Y (dec_sub_24_2_n_7));
  INVXL dec_sub_24_2_g171(.A (in1[7]), .Y (dec_sub_24_2_n_6));
  NAND2X1 dec_sub_24_2_g2(.A (dec_sub_24_2_n_29), .B
       (dec_sub_24_2_n_28), .Y (n_40));
  OR2XL dec_sub_24_2_g172(.A (dec_sub_24_2_n_19), .B
       (dec_sub_24_2_n_3), .Y (n_34));
  NOR2BX1 dec_sub_24_2_g173(.AN (dec_sub_24_2_n_11), .B (in1[2]), .Y
       (dec_sub_24_2_n_3));
  NOR3BXL dec_sub_24_2_g174(.AN (dec_sub_24_2_n_13), .B (in1[10]), .C
       (dec_sub_24_2_n_22), .Y (dec_sub_24_2_n_2));
  XOR2XL dec_sub_24_2_g175(.A (in1[3]), .B (dec_sub_24_2_n_3), .Y
       (n_35));
  XNOR2X1 dec_sub_24_2_g176(.A (in1[1]), .B (in1[0]), .Y (n_33));
endmodule


