`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Jan 27 2021 14:54:22 KST (Jan 27 2021 05:54:22 UTC)

module cache_Mul_5Ux4U_9U_1(in2, in1, out1);
  input [4:0] in2;
  input [3:0] in1;
  output [8:0] out1;
  wire [4:0] in2;
  wire [3:0] in1;
  wire [8:0] out1;
  wire mul_22_8_n_0, mul_22_8_n_1, mul_22_8_n_2, mul_22_8_n_3,
       mul_22_8_n_4, mul_22_8_n_5, mul_22_8_n_6, mul_22_8_n_10;
  wire mul_22_8_n_11, mul_22_8_n_12, mul_22_8_n_14, mul_22_8_n_15,
       mul_22_8_n_16, mul_22_8_n_17, mul_22_8_n_18, mul_22_8_n_19;
  wire mul_22_8_n_20, mul_22_8_n_21, mul_22_8_n_22, mul_22_8_n_23,
       mul_22_8_n_24, mul_22_8_n_25, mul_22_8_n_26, mul_22_8_n_27;
  wire mul_22_8_n_29, mul_22_8_n_30, mul_22_8_n_31, mul_22_8_n_32,
       mul_22_8_n_33, mul_22_8_n_34, mul_22_8_n_35, mul_22_8_n_36;
  wire mul_22_8_n_38, mul_22_8_n_40, mul_22_8_n_41, mul_22_8_n_42,
       mul_22_8_n_43, mul_22_8_n_44, mul_22_8_n_45, mul_22_8_n_46;
  wire mul_22_8_n_47, mul_22_8_n_48, mul_22_8_n_49, mul_22_8_n_51,
       mul_22_8_n_52, mul_22_8_n_54, mul_22_8_n_55, mul_22_8_n_56;
  wire mul_22_8_n_57, mul_22_8_n_58, mul_22_8_n_59, mul_22_8_n_60,
       mul_22_8_n_61, mul_22_8_n_62, mul_22_8_n_63, mul_22_8_n_64;
  wire mul_22_8_n_65, mul_22_8_n_66, mul_22_8_n_67, mul_22_8_n_68,
       mul_22_8_n_69, mul_22_8_n_70, mul_22_8_n_71, mul_22_8_n_73;
  wire mul_22_8_n_74, mul_22_8_n_75, mul_22_8_n_76, mul_22_8_n_77,
       mul_22_8_n_78, mul_22_8_n_79, mul_22_8_n_81, mul_22_8_n_82;
  wire mul_22_8_n_83, mul_22_8_n_84, mul_22_8_n_85, mul_22_8_n_86,
       mul_22_8_n_88, mul_22_8_n_89, mul_22_8_n_90, mul_22_8_n_91;
  wire mul_22_8_n_92, mul_22_8_n_93, mul_22_8_n_94, mul_22_8_n_95,
       mul_22_8_n_96, mul_22_8_n_97, mul_22_8_n_99, mul_22_8_n_111;
  wire mul_22_8_n_116, mul_22_8_n_117, mul_22_8_n_118, mul_22_8_n_120,
       mul_22_8_n_121;
  MXI2XL mul_22_8_g579(.A (mul_22_8_n_70), .B (mul_22_8_n_69), .S0
       (mul_22_8_n_99), .Y (out1[7]));
  AOI21X1 mul_22_8_g580(.A0 (mul_22_8_n_81), .A1 (mul_22_8_n_95), .B0
       (mul_22_8_n_78), .Y (mul_22_8_n_99));
  OAI2BB1X1 mul_22_8_g581(.A0N (mul_22_8_n_84), .A1N (mul_22_8_n_93),
       .B0 (mul_22_8_n_97), .Y (out1[8]));
  AOI21XL mul_22_8_g584(.A0 (mul_22_8_n_84), .A1 (mul_22_8_n_90), .B0
       (mul_22_8_n_91), .Y (mul_22_8_n_97));
  NOR2X1 mul_22_8_g585(.A (mul_22_8_n_90), .B (mul_22_8_n_93), .Y
       (mul_22_8_n_96));
  NAND2X1 mul_22_8_g586(.A (mul_22_8_n_89), .B (mul_22_8_n_92), .Y
       (mul_22_8_n_95));
  AOI21X1 mul_22_8_g587(.A0 (mul_22_8_n_116), .A1 (mul_22_8_n_88), .B0
       (mul_22_8_n_76), .Y (mul_22_8_n_94));
  INVX1 mul_22_8_g589(.A (mul_22_8_n_92), .Y (mul_22_8_n_93));
  NAND2X1 mul_22_8_g590(.A (mul_22_8_n_88), .B (mul_22_8_n_6), .Y
       (mul_22_8_n_92));
  OAI2BB1X1 mul_22_8_g591(.A0N (mul_22_8_n_66), .A1N (mul_22_8_n_78),
       .B0 (mul_22_8_n_65), .Y (mul_22_8_n_91));
  INVX1 mul_22_8_g592(.A (mul_22_8_n_89), .Y (mul_22_8_n_90));
  AOI21X1 mul_22_8_g593(.A0 (mul_22_8_n_76), .A1 (mul_22_8_n_79), .B0
       (mul_22_8_n_77), .Y (mul_22_8_n_89));
  ADDFX1 mul_22_8_g595(.A (mul_22_8_n_71), .B (mul_22_8_n_36), .CI
       (mul_22_8_n_4), .CO (mul_22_8_n_88), .S (out1[3]));
  NOR2BX1 mul_22_8_g598(.AN (mul_22_8_n_81), .B (mul_22_8_n_78), .Y
       (mul_22_8_n_86));
  NOR2BX1 mul_22_8_g600(.AN (mul_22_8_n_5), .B (mul_22_8_n_121), .Y
       (mul_22_8_n_85));
  AND2XL mul_22_8_g601(.A (mul_22_8_n_66), .B (mul_22_8_n_81), .Y
       (mul_22_8_n_84));
  NOR2BX1 mul_22_8_g602(.AN (mul_22_8_n_117), .B (mul_22_8_n_76), .Y
       (mul_22_8_n_83));
  NAND2X1 mul_22_8_g604(.A (mul_22_8_n_60), .B (mul_22_8_n_67), .Y
       (mul_22_8_n_82));
  OR2XL mul_22_8_g605(.A (mul_22_8_n_63), .B (mul_22_8_n_73), .Y
       (mul_22_8_n_81));
  NAND2X2 mul_22_8_g607(.A (mul_22_8_n_68), .B (mul_22_8_n_75), .Y
       (mul_22_8_n_79));
  AND2X1 mul_22_8_g608(.A (mul_22_8_n_63), .B (mul_22_8_n_73), .Y
       (mul_22_8_n_78));
  INVX1 mul_22_8_g609(.A (mul_22_8_n_5), .Y (mul_22_8_n_77));
  NOR2X1 mul_22_8_g611(.A (mul_22_8_n_60), .B (mul_22_8_n_67), .Y
       (mul_22_8_n_76));
  INVX1 mul_22_8_g612(.A (mul_22_8_n_74), .Y (mul_22_8_n_75));
  ADDFHXL mul_22_8_g613(.A (mul_22_8_n_55), .B (mul_22_8_n_12), .CI
       (mul_22_8_n_49), .CO (mul_22_8_n_73), .S (mul_22_8_n_74));
  ADDFX1 mul_22_8_g615(.A (mul_22_8_n_47), .B (mul_22_8_n_0), .CI
       (mul_22_8_n_51), .CO (mul_22_8_n_71), .S (out1[2]));
  INVXL mul_22_8_g616(.A (mul_22_8_n_69), .Y (mul_22_8_n_70));
  NAND2X1 mul_22_8_g617(.A (mul_22_8_n_65), .B (mul_22_8_n_66), .Y
       (mul_22_8_n_69));
  NOR2X1 mul_22_8_g618(.A (mul_22_8_n_59), .B (mul_22_8_n_64), .Y
       (mul_22_8_n_68));
  XNOR2X1 mul_22_8_g619(.A (mul_22_8_n_61), .B (mul_22_8_n_56), .Y
       (mul_22_8_n_67));
  NAND2BX1 mul_22_8_g620(.AN (mul_22_8_n_62), .B (mul_22_8_n_34), .Y
       (mul_22_8_n_66));
  NAND2BX1 mul_22_8_g621(.AN (mul_22_8_n_34), .B (mul_22_8_n_62), .Y
       (mul_22_8_n_65));
  NOR2X1 mul_22_8_g622(.A (mul_22_8_n_58), .B (mul_22_8_n_56), .Y
       (mul_22_8_n_64));
  ADDFX1 mul_22_8_g623(.A (mul_22_8_n_43), .B (mul_22_8_n_24), .CI
       (mul_22_8_n_23), .CO (mul_22_8_n_62), .S (mul_22_8_n_63));
  MXI2XL mul_22_8_g624(.A (mul_22_8_n_26), .B (mul_22_8_n_25), .S0
       (mul_22_8_n_42), .Y (mul_22_8_n_61));
  NOR2X1 mul_22_8_g625(.A (mul_22_8_n_46), .B (mul_22_8_n_57), .Y
       (mul_22_8_n_60));
  AND2XL mul_22_8_g627(.A (mul_22_8_n_26), .B (mul_22_8_n_42), .Y
       (mul_22_8_n_59));
  NOR2X1 mul_22_8_g628(.A (mul_22_8_n_26), .B (mul_22_8_n_42), .Y
       (mul_22_8_n_58));
  AOI21X1 mul_22_8_g629(.A0 (mul_22_8_n_19), .A1 (mul_22_8_n_20), .B0
       (mul_22_8_n_111), .Y (mul_22_8_n_57));
  MXI2X1 mul_22_8_g630(.A (mul_22_8_n_15), .B (mul_22_8_n_14), .S0
       (mul_22_8_n_52), .Y (mul_22_8_n_56));
  NAND2X2 mul_22_8_g632(.A (mul_22_8_n_45), .B (mul_22_8_n_54), .Y
       (mul_22_8_n_55));
  NAND2X2 mul_22_8_g633(.A (mul_22_8_n_1), .B (mul_22_8_n_40), .Y
       (mul_22_8_n_54));
  AOI21X1 mul_22_8_g634(.A0 (mul_22_8_n_35), .A1 (mul_22_8_n_22), .B0
       (mul_22_8_n_47), .Y (out1[1]));
  AOI31X1 mul_22_8_g635(.A0 (mul_22_8_n_16), .A1 (in2[4]), .A2
       (in1[0]), .B0 (mul_22_8_n_44), .Y (mul_22_8_n_52));
  MXI2X1 mul_22_8_g636(.A (mul_22_8_n_30), .B (mul_22_8_n_29), .S0
       (mul_22_8_n_21), .Y (mul_22_8_n_51));
  NAND2X2 mul_22_8_g638(.A (mul_22_8_n_2), .B (mul_22_8_n_3), .Y
       (mul_22_8_n_49));
  NOR2BX1 mul_22_8_g639(.AN (mul_22_8_n_38), .B (mul_22_8_n_41), .Y
       (mul_22_8_n_48));
  NOR2X1 mul_22_8_g640(.A (mul_22_8_n_19), .B (mul_22_8_n_20), .Y
       (mul_22_8_n_46));
  NAND2X4 mul_22_8_g642(.A (mul_22_8_n_14), .B (mul_22_8_n_17), .Y
       (mul_22_8_n_45));
  NOR2X2 mul_22_8_g644(.A (mul_22_8_n_16), .B (mul_22_8_n_1), .Y
       (mul_22_8_n_44));
  NOR2X1 mul_22_8_g645(.A (mul_22_8_n_31), .B (mul_22_8_n_32), .Y
       (mul_22_8_n_43));
  NOR2X1 mul_22_8_g646(.A (mul_22_8_n_35), .B (mul_22_8_n_22), .Y
       (mul_22_8_n_47));
  NOR2X1 mul_22_8_g647(.A (mul_22_8_n_18), .B (mul_22_8_n_20), .Y
       (mul_22_8_n_41));
  NAND2X4 mul_22_8_g648(.A (mul_22_8_n_15), .B (mul_22_8_n_16), .Y
       (mul_22_8_n_40));
  NAND2X1 mul_22_8_g650(.A (mul_22_8_n_20), .B (mul_22_8_n_18), .Y
       (mul_22_8_n_38));
  NOR2X1 mul_22_8_g652(.A (mul_22_8_n_21), .B (mul_22_8_n_29), .Y
       (mul_22_8_n_36));
  NOR2X1 mul_22_8_g653(.A (mul_22_8_n_27), .B (mul_22_8_n_33), .Y
       (mul_22_8_n_42));
  INVX1 mul_22_8_g656(.A (mul_22_8_n_29), .Y (mul_22_8_n_30));
  INVX1 mul_22_8_g658(.A (mul_22_8_n_25), .Y (mul_22_8_n_26));
  NAND2X1 mul_22_8_g659(.A (in2[0]), .B (in1[1]), .Y (mul_22_8_n_35));
  NAND2X1 mul_22_8_g660(.A (in2[4]), .B (in1[3]), .Y (mul_22_8_n_34));
  NAND2X2 mul_22_8_g661(.A (in2[3]), .B (in1[0]), .Y (mul_22_8_n_33));
  NAND2X4 mul_22_8_g662(.A (in2[4]), .B (in1[1]), .Y (mul_22_8_n_32));
  NAND2X8 mul_22_8_g663(.A (in2[3]), .B (in1[2]), .Y (mul_22_8_n_31));
  NAND2X2 mul_22_8_g664(.A (in2[2]), .B (in1[0]), .Y (mul_22_8_n_29));
  NAND2X1 mul_22_8_g665(.A (in2[2]), .B (in1[1]), .Y (mul_22_8_n_27));
  AND2XL mul_22_8_g666(.A (in2[4]), .B (in1[2]), .Y (mul_22_8_n_24));
  NAND2X1 mul_22_8_g667(.A (in2[1]), .B (in1[3]), .Y (mul_22_8_n_25));
  AND2XL mul_22_8_g668(.A (in2[3]), .B (in1[3]), .Y (mul_22_8_n_23));
  INVX1 mul_22_8_g669(.A (mul_22_8_n_18), .Y (mul_22_8_n_19));
  CLKINVX3 mul_22_8_g670(.A (mul_22_8_n_16), .Y (mul_22_8_n_17));
  CLKINVX4 mul_22_8_g671(.A (mul_22_8_n_15), .Y (mul_22_8_n_14));
  AND2XL mul_22_8_g672(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  NAND2X1 mul_22_8_g673(.A (in2[1]), .B (in1[0]), .Y (mul_22_8_n_22));
  NAND2X1 mul_22_8_g676(.A (in2[1]), .B (in1[1]), .Y (mul_22_8_n_21));
  NAND2X2 mul_22_8_g677(.A (in2[1]), .B (in1[2]), .Y (mul_22_8_n_20));
  NOR2X2 mul_22_8_g678(.A (mul_22_8_n_11), .B (mul_22_8_n_10), .Y
       (mul_22_8_n_18));
  NAND2X8 mul_22_8_g679(.A (in2[3]), .B (in1[1]), .Y (mul_22_8_n_16));
  NAND2X8 mul_22_8_g680(.A (in2[2]), .B (in1[2]), .Y (mul_22_8_n_15));
  AND2XL mul_22_8_g681(.A (in2[2]), .B (in1[3]), .Y (mul_22_8_n_12));
  INVX2 mul_22_8_g682(.A (in2[0]), .Y (mul_22_8_n_11));
  INVX1 mul_22_8_g683(.A (in1[3]), .Y (mul_22_8_n_10));
  CLKXOR2X1 mul_22_8_g2(.A (mul_22_8_n_88), .B (mul_22_8_n_83), .Y
       (out1[4]));
  XNOR2XL mul_22_8_g687(.A (mul_22_8_n_86), .B (mul_22_8_n_96), .Y
       (out1[6]));
  XNOR2XL mul_22_8_g688(.A (mul_22_8_n_85), .B (mul_22_8_n_94), .Y
       (out1[5]));
  NOR2BX1 mul_22_8_g689(.AN (mul_22_8_n_82), .B (mul_22_8_n_120), .Y
       (mul_22_8_n_6));
  NAND2BX1 mul_22_8_g690(.AN (mul_22_8_n_68), .B (mul_22_8_n_74), .Y
       (mul_22_8_n_5));
  XOR2XL mul_22_8_g691(.A (mul_22_8_n_48), .B (mul_22_8_n_111), .Y
       (mul_22_8_n_4));
  NAND2BX1 mul_22_8_g692(.AN (mul_22_8_n_32), .B (mul_22_8_n_31), .Y
       (mul_22_8_n_3));
  NAND2BX1 mul_22_8_g693(.AN (mul_22_8_n_31), .B (mul_22_8_n_32), .Y
       (mul_22_8_n_2));
  CLKAND2X6 mul_22_8_g694(.A (in2[4]), .B (in1[0]), .Y (mul_22_8_n_1));
  NOR2BX1 mul_22_8_g695(.AN (in1[2]), .B (mul_22_8_n_11), .Y
       (mul_22_8_n_0));
  XNOR2X1 mul_22_8_g697(.A (mul_22_8_n_33), .B (mul_22_8_n_27), .Y
       (mul_22_8_n_111));
  INVXL mul_22_8_fopt(.A (mul_22_8_n_118), .Y (mul_22_8_n_116));
  INVXL mul_22_8_fopt702(.A (mul_22_8_n_118), .Y (mul_22_8_n_117));
  INVXL mul_22_8_fopt703(.A (mul_22_8_n_82), .Y (mul_22_8_n_118));
  CLKINVX1 mul_22_8_fopt704(.A (mul_22_8_n_79), .Y (mul_22_8_n_120));
  INVXL mul_22_8_fopt705(.A (mul_22_8_n_79), .Y (mul_22_8_n_121));
endmodule


