`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Jan 27 2021 13:48:10 KST (Jan 27 2021 04:48:10 UTC)

module cache_Equal_8Ux2U_1U_4_0(in2, in1, out1);
  input [7:0] in2;
  input [1:0] in1;
  output out1;
  wire [7:0] in2;
  wire [1:0] in1;
  wire out1;
  wire n_0, n_1, n_2, n_3;
  NOR4X1 g45(.A (in2[3]), .B (n_0), .C (in2[2]), .D (n_3), .Y (out1));
  NAND2X1 g46(.A (n_2), .B (n_1), .Y (n_3));
  XNOR2X1 g48(.A (in2[1]), .B (in1[1]), .Y (n_2));
  XNOR2X1 g47(.A (in2[0]), .B (in1[0]), .Y (n_1));
  OR4X1 g49(.A (in2[7]), .B (in2[6]), .C (in2[5]), .D (in2[4]), .Y
       (n_0));
endmodule


