`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Jan 27 2021 13:48:37 KST (Jan 27 2021 04:48:37 UTC)

module cache_Mul_16Ux4U_20U_4_0(in2, in1, out1);
  input [15:0] in2;
  input [3:0] in1;
  output [19:0] out1;
  wire [15:0] in2;
  wire [3:0] in1;
  wire [19:0] out1;
  wire mul_22_8_n_0, mul_22_8_n_1, mul_22_8_n_2, mul_22_8_n_3,
       mul_22_8_n_4, mul_22_8_n_5, mul_22_8_n_6, mul_22_8_n_7;
  wire mul_22_8_n_8, mul_22_8_n_9, mul_22_8_n_10, mul_22_8_n_11,
       mul_22_8_n_12, mul_22_8_n_13, mul_22_8_n_14, mul_22_8_n_15;
  wire mul_22_8_n_16, mul_22_8_n_17, mul_22_8_n_18, mul_22_8_n_19,
       mul_22_8_n_20, mul_22_8_n_21, mul_22_8_n_22, mul_22_8_n_23;
  wire mul_22_8_n_24, mul_22_8_n_25, mul_22_8_n_26, mul_22_8_n_27,
       mul_22_8_n_28, mul_22_8_n_29, mul_22_8_n_30, mul_22_8_n_32;
  wire mul_22_8_n_33, mul_22_8_n_34, mul_22_8_n_35, mul_22_8_n_36,
       mul_22_8_n_37, mul_22_8_n_38, mul_22_8_n_39, mul_22_8_n_40;
  wire mul_22_8_n_41, mul_22_8_n_42, mul_22_8_n_43, mul_22_8_n_44,
       mul_22_8_n_45, mul_22_8_n_46, mul_22_8_n_47, mul_22_8_n_48;
  wire mul_22_8_n_49, mul_22_8_n_50, mul_22_8_n_51, mul_22_8_n_52,
       mul_22_8_n_53, mul_22_8_n_54, mul_22_8_n_55, mul_22_8_n_56;
  wire mul_22_8_n_57, mul_22_8_n_58, mul_22_8_n_59, mul_22_8_n_60,
       mul_22_8_n_61, mul_22_8_n_62, mul_22_8_n_63, mul_22_8_n_64;
  wire mul_22_8_n_66, mul_22_8_n_67, mul_22_8_n_68, mul_22_8_n_69,
       mul_22_8_n_70, mul_22_8_n_71, mul_22_8_n_72, mul_22_8_n_73;
  wire mul_22_8_n_74, mul_22_8_n_75, mul_22_8_n_76, mul_22_8_n_77,
       mul_22_8_n_78, mul_22_8_n_79, mul_22_8_n_80, mul_22_8_n_81;
  wire mul_22_8_n_82, mul_22_8_n_83, mul_22_8_n_84, mul_22_8_n_85,
       mul_22_8_n_86, mul_22_8_n_87, mul_22_8_n_88, mul_22_8_n_89;
  wire mul_22_8_n_90, mul_22_8_n_91, mul_22_8_n_92, mul_22_8_n_93,
       mul_22_8_n_94, mul_22_8_n_95, mul_22_8_n_96, mul_22_8_n_97;
  wire mul_22_8_n_98, mul_22_8_n_99, mul_22_8_n_100, mul_22_8_n_102,
       mul_22_8_n_103, mul_22_8_n_104, mul_22_8_n_105, mul_22_8_n_106;
  wire mul_22_8_n_107, mul_22_8_n_108, mul_22_8_n_109, mul_22_8_n_110,
       mul_22_8_n_111, mul_22_8_n_112, mul_22_8_n_113, mul_22_8_n_114;
  wire mul_22_8_n_115, mul_22_8_n_116, mul_22_8_n_117, mul_22_8_n_118,
       mul_22_8_n_119, mul_22_8_n_120, mul_22_8_n_121, mul_22_8_n_122;
  wire mul_22_8_n_123, mul_22_8_n_125, mul_22_8_n_126, mul_22_8_n_127,
       mul_22_8_n_128, mul_22_8_n_129, mul_22_8_n_130, mul_22_8_n_131;
  wire mul_22_8_n_132, mul_22_8_n_133, mul_22_8_n_134, mul_22_8_n_135,
       mul_22_8_n_136, mul_22_8_n_137, mul_22_8_n_138, mul_22_8_n_139;
  wire mul_22_8_n_140, mul_22_8_n_141, mul_22_8_n_142, mul_22_8_n_143,
       mul_22_8_n_144, mul_22_8_n_145, mul_22_8_n_146, mul_22_8_n_147;
  wire mul_22_8_n_148, mul_22_8_n_149, mul_22_8_n_150, mul_22_8_n_151,
       mul_22_8_n_152, mul_22_8_n_153, mul_22_8_n_154, mul_22_8_n_155;
  wire mul_22_8_n_156, mul_22_8_n_157, mul_22_8_n_158, mul_22_8_n_159,
       mul_22_8_n_161, mul_22_8_n_162, mul_22_8_n_163, mul_22_8_n_164;
  wire mul_22_8_n_165, mul_22_8_n_166, mul_22_8_n_167, mul_22_8_n_168,
       mul_22_8_n_169, mul_22_8_n_170, mul_22_8_n_171, mul_22_8_n_172;
  wire mul_22_8_n_173, mul_22_8_n_174, mul_22_8_n_175, mul_22_8_n_176,
       mul_22_8_n_177, mul_22_8_n_178, mul_22_8_n_179, mul_22_8_n_180;
  wire mul_22_8_n_181, mul_22_8_n_182, mul_22_8_n_183, mul_22_8_n_185,
       mul_22_8_n_186, mul_22_8_n_187, mul_22_8_n_188, mul_22_8_n_189;
  wire mul_22_8_n_190, mul_22_8_n_191, mul_22_8_n_193, mul_22_8_n_194,
       mul_22_8_n_195, mul_22_8_n_196, mul_22_8_n_199, mul_22_8_n_200;
  wire mul_22_8_n_201, mul_22_8_n_202, mul_22_8_n_203, mul_22_8_n_206,
       mul_22_8_n_207, mul_22_8_n_209, mul_22_8_n_210, mul_22_8_n_213;
  wire mul_22_8_n_214, mul_22_8_n_217, mul_22_8_n_219;
  ADDFX1 mul_22_8_g2011(.A (mul_22_8_n_219), .B (mul_22_8_n_88), .CI
       (mul_22_8_n_30), .CO (out1[19]), .S (out1[18]));
  XNOR2X1 mul_22_8_g2012(.A (mul_22_8_n_139), .B (mul_22_8_n_217), .Y
       (out1[15]));
  OAI21X1 mul_22_8_g2013(.A0 (mul_22_8_n_107), .A1 (mul_22_8_n_214),
       .B0 (mul_22_8_n_109), .Y (mul_22_8_n_219));
  XNOR2X1 mul_22_8_g2014(.A (mul_22_8_n_121), .B (mul_22_8_n_213), .Y
       (out1[17]));
  OAI21X1 mul_22_8_g2015(.A0 (mul_22_8_n_150), .A1 (mul_22_8_n_210),
       .B0 (mul_22_8_n_141), .Y (mul_22_8_n_217));
  XNOR2X1 mul_22_8_g2016(.A (mul_22_8_n_158), .B (mul_22_8_n_210), .Y
       (out1[14]));
  XNOR2X1 mul_22_8_g2017(.A (mul_22_8_n_180), .B (mul_22_8_n_209), .Y
       (out1[13]));
  OA21X1 mul_22_8_g2018(.A0 (mul_22_8_n_126), .A1 (mul_22_8_n_207), .B0
       (mul_22_8_n_122), .Y (mul_22_8_n_214));
  OAI21X1 mul_22_8_g2019(.A0 (mul_22_8_n_126), .A1 (mul_22_8_n_207),
       .B0 (mul_22_8_n_122), .Y (mul_22_8_n_213));
  XNOR2X1 mul_22_8_g2020(.A (mul_22_8_n_138), .B (mul_22_8_n_207), .Y
       (out1[16]));
  XNOR2X1 mul_22_8_g2021(.A (mul_22_8_n_157), .B (mul_22_8_n_206), .Y
       (out1[11]));
  AOI21X1 mul_22_8_g2022(.A0 (mul_22_8_n_183), .A1 (mul_22_8_n_203),
       .B0 (mul_22_8_n_186), .Y (mul_22_8_n_210));
  OAI2BB1X1 mul_22_8_g2023(.A0N (mul_22_8_n_161), .A1N
       (mul_22_8_n_203), .B0 (mul_22_8_n_163), .Y (mul_22_8_n_209));
  XNOR2X1 mul_22_8_g2024(.A (mul_22_8_n_179), .B (mul_22_8_n_203), .Y
       (out1[12]));
  AOI2BB1X1 mul_22_8_g2025(.A0N (mul_22_8_n_188), .A1N
       (mul_22_8_n_199), .B0 (mul_22_8_n_202), .Y (mul_22_8_n_207));
  OAI21X1 mul_22_8_g2026(.A0 (mul_22_8_n_146), .A1 (mul_22_8_n_201),
       .B0 (mul_22_8_n_142), .Y (mul_22_8_n_206));
  XNOR2X1 mul_22_8_g2027(.A (mul_22_8_n_156), .B (mul_22_8_n_201), .Y
       (out1[10]));
  XNOR2X1 mul_22_8_g2028(.A (mul_22_8_n_178), .B (mul_22_8_n_200), .Y
       (out1[9]));
  NAND2BX1 mul_22_8_g2029(.AN (mul_22_8_n_190), .B (mul_22_8_n_199), .Y
       (mul_22_8_n_203));
  OAI211X1 mul_22_8_g2030(.A0 (mul_22_8_n_188), .A1 (mul_22_8_n_191),
       .B0 (mul_22_8_n_193), .C0 (mul_22_8_n_123), .Y (mul_22_8_n_202));
  AOI21X1 mul_22_8_g2031(.A0 (mul_22_8_n_182), .A1 (mul_22_8_n_195),
       .B0 (mul_22_8_n_185), .Y (mul_22_8_n_201));
  OAI21X1 mul_22_8_g2032(.A0 (mul_22_8_n_169), .A1 (mul_22_8_n_196),
       .B0 (mul_22_8_n_162), .Y (mul_22_8_n_200));
  NAND3X1 mul_22_8_g2033(.A (mul_22_8_n_171), .B (mul_22_8_n_182), .C
       (mul_22_8_n_195), .Y (mul_22_8_n_199));
  XNOR2X1 mul_22_8_g2034(.A (mul_22_8_n_181), .B (mul_22_8_n_196), .Y
       (out1[8]));
  XNOR2X1 mul_22_8_g2035(.A (mul_22_8_n_140), .B (mul_22_8_n_194), .Y
       (out1[7]));
  INVX1 mul_22_8_g2036(.A (mul_22_8_n_196), .Y (mul_22_8_n_195));
  AOI221X1 mul_22_8_g2037(.A0 (mul_22_8_n_173), .A1 (mul_22_8_n_176),
       .B0 (mul_22_8_n_173), .B1 (mul_22_8_n_172), .C0
       (mul_22_8_n_177), .Y (mul_22_8_n_196));
  OAI21X1 mul_22_8_g2038(.A0 (mul_22_8_n_145), .A1 (mul_22_8_n_187),
       .B0 (mul_22_8_n_148), .Y (mul_22_8_n_194));
  AOI21XL mul_22_8_g2039(.A0 (mul_22_8_n_174), .A1 (mul_22_8_n_186),
       .B0 (mul_22_8_n_168), .Y (mul_22_8_n_193));
  XNOR2X1 mul_22_8_g2040(.A (mul_22_8_n_166), .B (mul_22_8_n_187), .Y
       (out1[6]));
  INVX1 mul_22_8_g2041(.A (mul_22_8_n_190), .Y (mul_22_8_n_191));
  OAI211X1 mul_22_8_g2042(.A0 (mul_22_8_n_142), .A1 (mul_22_8_n_147),
       .B0 (mul_22_8_n_189), .C0 (mul_22_8_n_143), .Y (mul_22_8_n_190));
  NAND2XL mul_22_8_g2043(.A (mul_22_8_n_171), .B (mul_22_8_n_185), .Y
       (mul_22_8_n_189));
  NAND2XL mul_22_8_g2044(.A (mul_22_8_n_183), .B (mul_22_8_n_174), .Y
       (mul_22_8_n_188));
  NOR2X1 mul_22_8_g2045(.A (mul_22_8_n_172), .B (mul_22_8_n_176), .Y
       (mul_22_8_n_187));
  OAI21X1 mul_22_8_g2046(.A0 (mul_22_8_n_163), .A1 (mul_22_8_n_170),
       .B0 (mul_22_8_n_175), .Y (mul_22_8_n_186));
  OAI21X1 mul_22_8_g2047(.A0 (mul_22_8_n_164), .A1 (mul_22_8_n_162),
       .B0 (mul_22_8_n_165), .Y (mul_22_8_n_185));
  XNOR2X1 mul_22_8_g2048(.A (mul_22_8_n_167), .B (mul_22_8_n_159), .Y
       (out1[5]));
  NOR2BX1 mul_22_8_g2049(.AN (mul_22_8_n_161), .B (mul_22_8_n_170), .Y
       (mul_22_8_n_183));
  NOR2X1 mul_22_8_g2050(.A (mul_22_8_n_164), .B (mul_22_8_n_169), .Y
       (mul_22_8_n_182));
  NOR2BX1 mul_22_8_g2051(.AN (mul_22_8_n_162), .B (mul_22_8_n_169), .Y
       (mul_22_8_n_181));
  NAND2BX1 mul_22_8_g2052(.AN (mul_22_8_n_170), .B (mul_22_8_n_175), .Y
       (mul_22_8_n_180));
  NAND2X1 mul_22_8_g2053(.A (mul_22_8_n_163), .B (mul_22_8_n_161), .Y
       (mul_22_8_n_179));
  NAND2BX1 mul_22_8_g2054(.AN (mul_22_8_n_164), .B (mul_22_8_n_165), .Y
       (mul_22_8_n_178));
  OAI21X1 mul_22_8_g2055(.A0 (mul_22_8_n_148), .A1 (mul_22_8_n_125),
       .B0 (mul_22_8_n_128), .Y (mul_22_8_n_177));
  OAI21X1 mul_22_8_g2056(.A0 (mul_22_8_n_106), .A1 (mul_22_8_n_149),
       .B0 (mul_22_8_n_144), .Y (mul_22_8_n_176));
  NOR2XL mul_22_8_g2057(.A (mul_22_8_n_141), .B (mul_22_8_n_127), .Y
       (mul_22_8_n_168));
  NAND2BX1 mul_22_8_g2058(.AN (mul_22_8_n_149), .B (mul_22_8_n_144), .Y
       (mul_22_8_n_167));
  NAND2X1 mul_22_8_g2059(.A (mul_22_8_n_152), .B (mul_22_8_n_133), .Y
       (mul_22_8_n_175));
  NOR2XL mul_22_8_g2060(.A (mul_22_8_n_127), .B (mul_22_8_n_150), .Y
       (mul_22_8_n_174));
  NOR2X1 mul_22_8_g2061(.A (mul_22_8_n_145), .B (mul_22_8_n_125), .Y
       (mul_22_8_n_173));
  NOR2BX1 mul_22_8_g2062(.AN (mul_22_8_n_148), .B (mul_22_8_n_145), .Y
       (mul_22_8_n_166));
  NOR2X1 mul_22_8_g2063(.A (mul_22_8_n_149), .B (mul_22_8_n_151), .Y
       (mul_22_8_n_172));
  NOR2XL mul_22_8_g2064(.A (mul_22_8_n_147), .B (mul_22_8_n_146), .Y
       (mul_22_8_n_171));
  NOR2X1 mul_22_8_g2065(.A (mul_22_8_n_152), .B (mul_22_8_n_133), .Y
       (mul_22_8_n_170));
  NOR2X1 mul_22_8_g2066(.A (mul_22_8_n_116), .B (mul_22_8_n_155), .Y
       (mul_22_8_n_169));
  XNOR2X1 mul_22_8_g2067(.A (mul_22_8_n_131), .B (mul_22_8_n_120), .Y
       (out1[4]));
  NAND2X1 mul_22_8_g2068(.A (mul_22_8_n_106), .B (mul_22_8_n_151), .Y
       (mul_22_8_n_159));
  NOR2BX1 mul_22_8_g2069(.AN (mul_22_8_n_141), .B (mul_22_8_n_150), .Y
       (mul_22_8_n_158));
  NAND2BX1 mul_22_8_g2070(.AN (mul_22_8_n_147), .B (mul_22_8_n_143), .Y
       (mul_22_8_n_157));
  NOR2BX1 mul_22_8_g2071(.AN (mul_22_8_n_142), .B (mul_22_8_n_146), .Y
       (mul_22_8_n_156));
  NAND2X1 mul_22_8_g2072(.A (mul_22_8_n_154), .B (mul_22_8_n_119), .Y
       (mul_22_8_n_165));
  NOR2X1 mul_22_8_g2073(.A (mul_22_8_n_154), .B (mul_22_8_n_119), .Y
       (mul_22_8_n_164));
  NAND2X1 mul_22_8_g2074(.A (mul_22_8_n_136), .B (mul_22_8_n_153), .Y
       (mul_22_8_n_163));
  NAND2X1 mul_22_8_g2075(.A (mul_22_8_n_116), .B (mul_22_8_n_155), .Y
       (mul_22_8_n_162));
  OR2XL mul_22_8_g2076(.A (mul_22_8_n_136), .B (mul_22_8_n_153), .Y
       (mul_22_8_n_161));
  ADDFX1 mul_22_8_g2077(.A (mul_22_8_n_79), .B (mul_22_8_n_96), .CI
       (mul_22_8_n_46), .CO (mul_22_8_n_154), .S (mul_22_8_n_155));
  ADDFX1 mul_22_8_g2078(.A (mul_22_8_n_99), .B (mul_22_8_n_94), .CI
       (mul_22_8_n_52), .CO (mul_22_8_n_152), .S (mul_22_8_n_153));
  NAND2X1 mul_22_8_g2079(.A (mul_22_8_n_108), .B (mul_22_8_n_131), .Y
       (mul_22_8_n_151));
  NOR2X1 mul_22_8_g2080(.A (mul_22_8_n_132), .B (mul_22_8_n_111), .Y
       (mul_22_8_n_150));
  NOR2X1 mul_22_8_g2081(.A (mul_22_8_n_102), .B (mul_22_8_n_135), .Y
       (mul_22_8_n_149));
  NAND2X1 mul_22_8_g2082(.A (mul_22_8_n_134), .B (mul_22_8_n_113), .Y
       (mul_22_8_n_148));
  NOR2X1 mul_22_8_g2083(.A (mul_22_8_n_129), .B (mul_22_8_n_137), .Y
       (mul_22_8_n_147));
  NOR2X1 mul_22_8_g2084(.A (mul_22_8_n_118), .B (mul_22_8_n_130), .Y
       (mul_22_8_n_146));
  NOR2X1 mul_22_8_g2085(.A (mul_22_8_n_134), .B (mul_22_8_n_113), .Y
       (mul_22_8_n_145));
  NAND2BX1 mul_22_8_g2086(.AN (mul_22_8_n_125), .B (mul_22_8_n_128), .Y
       (mul_22_8_n_140));
  NAND2X1 mul_22_8_g2087(.A (mul_22_8_n_102), .B (mul_22_8_n_135), .Y
       (mul_22_8_n_144));
  NAND2X1 mul_22_8_g2088(.A (mul_22_8_n_129), .B (mul_22_8_n_137), .Y
       (mul_22_8_n_143));
  NAND2BX1 mul_22_8_g2089(.AN (mul_22_8_n_127), .B (mul_22_8_n_123), .Y
       (mul_22_8_n_139));
  NOR2BX1 mul_22_8_g2090(.AN (mul_22_8_n_122), .B (mul_22_8_n_126), .Y
       (mul_22_8_n_138));
  NAND2X1 mul_22_8_g2091(.A (mul_22_8_n_118), .B (mul_22_8_n_130), .Y
       (mul_22_8_n_142));
  NAND2X1 mul_22_8_g2092(.A (mul_22_8_n_132), .B (mul_22_8_n_111), .Y
       (mul_22_8_n_141));
  ADDFX1 mul_22_8_g2093(.A (mul_22_8_n_95), .B (mul_22_8_n_82), .CI
       (mul_22_8_n_44), .CO (mul_22_8_n_136), .S (mul_22_8_n_137));
  ADDFX1 mul_22_8_g2094(.A (mul_22_8_n_87), .B (mul_22_8_n_76), .CI
       (mul_22_8_n_47), .CO (mul_22_8_n_134), .S (mul_22_8_n_135));
  ADDFX1 mul_22_8_g2095(.A (mul_22_8_n_98), .B (mul_22_8_n_14), .CI
       (mul_22_8_n_75), .CO (mul_22_8_n_132), .S (mul_22_8_n_133));
  ADDFX1 mul_22_8_g2096(.A (mul_22_8_n_100), .B (mul_22_8_n_66), .CI
       (mul_22_8_n_92), .CO (mul_22_8_n_131), .S (out1[3]));
  ADDFX1 mul_22_8_g2097(.A (mul_22_8_n_90), .B (mul_22_8_n_48), .CI
       (mul_22_8_n_83), .CO (mul_22_8_n_129), .S (mul_22_8_n_130));
  NAND2X1 mul_22_8_g2098(.A (mul_22_8_n_112), .B (mul_22_8_n_117), .Y
       (mul_22_8_n_128));
  NOR2X1 mul_22_8_g2099(.A (mul_22_8_n_110), .B (mul_22_8_n_115), .Y
       (mul_22_8_n_127));
  NOR2X1 mul_22_8_g2100(.A (mul_22_8_n_114), .B (mul_22_8_n_105), .Y
       (mul_22_8_n_126));
  NOR2X1 mul_22_8_g2101(.A (mul_22_8_n_112), .B (mul_22_8_n_117), .Y
       (mul_22_8_n_125));
  NAND2BXL mul_22_8_g2102(.AN (mul_22_8_n_107), .B (mul_22_8_n_109), .Y
       (mul_22_8_n_121));
  NAND2X1 mul_22_8_g2103(.A (mul_22_8_n_106), .B (mul_22_8_n_108), .Y
       (mul_22_8_n_120));
  NAND2X1 mul_22_8_g2104(.A (mul_22_8_n_110), .B (mul_22_8_n_115), .Y
       (mul_22_8_n_123));
  NAND2XL mul_22_8_g2105(.A (mul_22_8_n_114), .B (mul_22_8_n_105), .Y
       (mul_22_8_n_122));
  ADDFX1 mul_22_8_g2106(.A (mul_22_8_n_78), .B (mul_22_8_n_1), .CI
       (mul_22_8_n_91), .CO (mul_22_8_n_118), .S (mul_22_8_n_119));
  ADDFX1 mul_22_8_g2107(.A (mul_22_8_n_80), .B (mul_22_8_n_8), .CI
       (mul_22_8_n_97), .CO (mul_22_8_n_116), .S (mul_22_8_n_117));
  ADDFX1 mul_22_8_g2108(.A (mul_22_8_n_72), .B (mul_22_8_n_37), .CI
       (mul_22_8_n_85), .CO (mul_22_8_n_114), .S (mul_22_8_n_115));
  ADDFX1 mul_22_8_g2109(.A (mul_22_8_n_86), .B (mul_22_8_n_6), .CI
       (mul_22_8_n_81), .CO (mul_22_8_n_112), .S (mul_22_8_n_113));
  ADDFX1 mul_22_8_g2110(.A (mul_22_8_n_74), .B (mul_22_8_n_2), .CI
       (mul_22_8_n_73), .CO (mul_22_8_n_110), .S (mul_22_8_n_111));
  NAND2XL mul_22_8_g2111(.A (mul_22_8_n_89), .B (mul_22_8_n_104), .Y
       (mul_22_8_n_109));
  OR2X1 mul_22_8_g2112(.A (mul_22_8_n_93), .B (mul_22_8_n_103), .Y
       (mul_22_8_n_108));
  NOR2X1 mul_22_8_g2113(.A (mul_22_8_n_89), .B (mul_22_8_n_104), .Y
       (mul_22_8_n_107));
  NAND2X1 mul_22_8_g2114(.A (mul_22_8_n_93), .B (mul_22_8_n_103), .Y
       (mul_22_8_n_106));
  ADDFX1 mul_22_8_g2115(.A (mul_22_8_n_84), .B (mul_22_8_n_69), .CI
       (mul_22_8_n_45), .CO (mul_22_8_n_104), .S (mul_22_8_n_105));
  ADDFX1 mul_22_8_g2116(.A (mul_22_8_n_77), .B (mul_22_8_n_70), .CI
       (mul_22_8_n_15), .CO (mul_22_8_n_102), .S (mul_22_8_n_103));
  ADDFX1 mul_22_8_g2117(.A (mul_22_8_n_64), .B (mul_22_8_n_61), .CI
       (mul_22_8_n_67), .CO (mul_22_8_n_100), .S (out1[2]));
  ADDFX1 mul_22_8_g2118(.A (mul_22_8_n_25), .B (mul_22_8_n_36), .CI
       (mul_22_8_n_38), .CO (mul_22_8_n_98), .S (mul_22_8_n_99));
  ADDFX1 mul_22_8_g2119(.A (mul_22_8_n_24), .B (mul_22_8_n_0), .CI
       (mul_22_8_n_41), .CO (mul_22_8_n_96), .S (mul_22_8_n_97));
  ADDFX1 mul_22_8_g2120(.A (mul_22_8_n_29), .B (mul_22_8_n_42), .CI
       (mul_22_8_n_13), .CO (mul_22_8_n_94), .S (mul_22_8_n_95));
  ADDFX1 mul_22_8_g2121(.A (mul_22_8_n_71), .B (mul_22_8_n_4), .CI
       (mul_22_8_n_35), .CO (mul_22_8_n_93), .S (mul_22_8_n_92));
  ADDFX1 mul_22_8_g2122(.A (mul_22_8_n_26), .B (mul_22_8_n_10), .CI
       (mul_22_8_n_32), .CO (mul_22_8_n_90), .S (mul_22_8_n_91));
  ADDFX1 mul_22_8_g2123(.A (mul_22_8_n_68), .B (mul_22_8_n_33), .CI
       (mul_22_8_n_18), .CO (mul_22_8_n_88), .S (mul_22_8_n_89));
  ADDFX1 mul_22_8_g2124(.A (mul_22_8_n_60), .B (mul_22_8_n_16), .CI
       (mul_22_8_n_5), .CO (mul_22_8_n_86), .S (mul_22_8_n_87));
  ADDFX1 mul_22_8_g2125(.A (mul_22_8_n_59), .B (mul_22_8_n_7), .CI
       (mul_22_8_n_19), .CO (mul_22_8_n_84), .S (mul_22_8_n_85));
  ADDFX1 mul_22_8_g2126(.A (mul_22_8_n_57), .B (mul_22_8_n_9), .CI
       (mul_22_8_n_49), .CO (mul_22_8_n_82), .S (mul_22_8_n_83));
  ADDFX1 mul_22_8_g2127(.A (mul_22_8_n_22), .B (mul_22_8_n_11), .CI
       (mul_22_8_n_50), .CO (mul_22_8_n_80), .S (mul_22_8_n_81));
  ADDFX1 mul_22_8_g2128(.A (mul_22_8_n_53), .B (mul_22_8_n_39), .CI
       (mul_22_8_n_43), .CO (mul_22_8_n_78), .S (mul_22_8_n_79));
  ADDFX1 mul_22_8_g2129(.A (mul_22_8_n_21), .B (mul_22_8_n_51), .CI
       (mul_22_8_n_40), .CO (mul_22_8_n_76), .S (mul_22_8_n_77));
  ADDFX1 mul_22_8_g2130(.A (mul_22_8_n_56), .B (mul_22_8_n_3), .CI
       (mul_22_8_n_17), .CO (mul_22_8_n_74), .S (mul_22_8_n_75));
  ADDFX1 mul_22_8_g2131(.A (mul_22_8_n_55), .B (mul_22_8_n_34), .CI
       (mul_22_8_n_12), .CO (mul_22_8_n_72), .S (mul_22_8_n_73));
  ADDHX1 mul_22_8_g2132(.A (mul_22_8_n_27), .B (mul_22_8_n_28), .CO
       (mul_22_8_n_70), .S (mul_22_8_n_71));
  ADDHX1 mul_22_8_g2133(.A (mul_22_8_n_54), .B (mul_22_8_n_23), .CO
       (mul_22_8_n_68), .S (mul_22_8_n_69));
  ADDHX1 mul_22_8_g2134(.A (mul_22_8_n_20), .B (mul_22_8_n_58), .CO
       (mul_22_8_n_66), .S (mul_22_8_n_67));
  AOI21X1 mul_22_8_g2135(.A0 (mul_22_8_n_62), .A1 (mul_22_8_n_63), .B0
       (mul_22_8_n_64), .Y (out1[1]));
  NOR2X1 mul_22_8_g2136(.A (mul_22_8_n_62), .B (mul_22_8_n_63), .Y
       (mul_22_8_n_64));
  AND2XL mul_22_8_g2137(.A (in2[0]), .B (in1[2]), .Y (mul_22_8_n_61));
  NAND2X1 mul_22_8_g2138(.A (in2[1]), .B (in1[0]), .Y (mul_22_8_n_63));
  NAND2X1 mul_22_8_g2139(.A (in2[0]), .B (in1[1]), .Y (mul_22_8_n_62));
  AND2XL mul_22_8_g2140(.A (in2[4]), .B (in1[1]), .Y (mul_22_8_n_60));
  AND2XL mul_22_8_g2141(.A (in2[14]), .B (in1[1]), .Y (mul_22_8_n_59));
  AND2XL mul_22_8_g2142(.A (in2[2]), .B (in1[0]), .Y (mul_22_8_n_58));
  AND2XL mul_22_8_g2143(.A (in2[9]), .B (in1[1]), .Y (mul_22_8_n_57));
  AND2XL mul_22_8_g2144(.A (in2[12]), .B (in1[1]), .Y (mul_22_8_n_56));
  AND2XL mul_22_8_g2145(.A (in2[13]), .B (in1[1]), .Y (mul_22_8_n_55));
  AND2XL mul_22_8_g2146(.A (in2[14]), .B (in1[2]), .Y (mul_22_8_n_54));
  AND2XL mul_22_8_g2147(.A (in2[7]), .B (in1[1]), .Y (mul_22_8_n_53));
  AND2XL mul_22_8_g2148(.A (in2[9]), .B (in1[3]), .Y (mul_22_8_n_52));
  AND2XL mul_22_8_g2149(.A (in2[4]), .B (in1[0]), .Y (mul_22_8_n_51));
  AND2XL mul_22_8_g2150(.A (in2[4]), .B (in1[2]), .Y (mul_22_8_n_50));
  AND2XL mul_22_8_g2151(.A (in2[8]), .B (in1[2]), .Y (mul_22_8_n_49));
  AND2XL mul_22_8_g2152(.A (in2[7]), .B (in1[3]), .Y (mul_22_8_n_48));
  AND2XL mul_22_8_g2153(.A (in2[2]), .B (in1[3]), .Y (mul_22_8_n_47));
  AND2XL mul_22_8_g2154(.A (in2[5]), .B (in1[3]), .Y (mul_22_8_n_46));
  AND2XL mul_22_8_g2155(.A (in2[13]), .B (in1[3]), .Y (mul_22_8_n_45));
  AND2XL mul_22_8_g2156(.A (in2[8]), .B (in1[3]), .Y (mul_22_8_n_44));
  AND2XL mul_22_8_g2157(.A (in2[6]), .B (in1[2]), .Y (mul_22_8_n_43));
  AND2XL mul_22_8_g2158(.A (in2[11]), .B (in1[0]), .Y (mul_22_8_n_42));
  AND2XL mul_22_8_g2159(.A (in2[6]), .B (in1[1]), .Y (mul_22_8_n_41));
  AND2XL mul_22_8_g2160(.A (in2[2]), .B (in1[2]), .Y (mul_22_8_n_40));
  AND2XL mul_22_8_g2161(.A (in2[8]), .B (in1[0]), .Y (mul_22_8_n_39));
  AND2XL mul_22_8_g2162(.A (in2[11]), .B (in1[1]), .Y (mul_22_8_n_38));
  AND2XL mul_22_8_g2163(.A (in2[12]), .B (in1[3]), .Y (mul_22_8_n_37));
  AND2XL mul_22_8_g2164(.A (in2[12]), .B (in1[0]), .Y (mul_22_8_n_36));
  AND2XL mul_22_8_g2165(.A (in2[0]), .B (in1[3]), .Y (mul_22_8_n_35));
  AND2XL mul_22_8_g2166(.A (in2[12]), .B (in1[2]), .Y (mul_22_8_n_34));
  AND2XL mul_22_8_g2167(.A (in2[15]), .B (in1[2]), .Y (mul_22_8_n_33));
  AND2XL mul_22_8_g2168(.A (in2[8]), .B (in1[1]), .Y (mul_22_8_n_32));
  AND2XL mul_22_8_g2169(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  AND2XL mul_22_8_g2170(.A (in2[15]), .B (in1[3]), .Y (mul_22_8_n_30));
  AND2XL mul_22_8_g2171(.A (in2[9]), .B (in1[2]), .Y (mul_22_8_n_29));
  AND2XL mul_22_8_g2172(.A (in2[3]), .B (in1[0]), .Y (mul_22_8_n_28));
  AND2XL mul_22_8_g2173(.A (in2[2]), .B (in1[1]), .Y (mul_22_8_n_27));
  AND2XL mul_22_8_g2174(.A (in2[7]), .B (in1[2]), .Y (mul_22_8_n_26));
  AND2XL mul_22_8_g2175(.A (in2[10]), .B (in1[2]), .Y (mul_22_8_n_25));
  AND2XL mul_22_8_g2176(.A (in2[5]), .B (in1[2]), .Y (mul_22_8_n_24));
  AND2XL mul_22_8_g2177(.A (in2[15]), .B (in1[1]), .Y (mul_22_8_n_23));
  AND2XL mul_22_8_g2178(.A (in2[6]), .B (in1[0]), .Y (mul_22_8_n_22));
  AND2XL mul_22_8_g2179(.A (in2[3]), .B (in1[1]), .Y (mul_22_8_n_21));
  AND2XL mul_22_8_g2180(.A (in2[1]), .B (in1[1]), .Y (mul_22_8_n_20));
  AND2XL mul_22_8_g2181(.A (in2[13]), .B (in1[2]), .Y (mul_22_8_n_19));
  AND2XL mul_22_8_g2182(.A (in2[14]), .B (in1[3]), .Y (mul_22_8_n_18));
  AND2XL mul_22_8_g2183(.A (in2[13]), .B (in1[0]), .Y (mul_22_8_n_17));
  AND2XL mul_22_8_g2184(.A (in2[5]), .B (in1[0]), .Y (mul_22_8_n_16));
  AND2XL mul_22_8_g2185(.A (in2[1]), .B (in1[3]), .Y (mul_22_8_n_15));
  AND2XL mul_22_8_g2186(.A (in2[10]), .B (in1[3]), .Y (mul_22_8_n_14));
  AND2XL mul_22_8_g2187(.A (in2[10]), .B (in1[1]), .Y (mul_22_8_n_13));
  AND2XL mul_22_8_g2188(.A (in2[14]), .B (in1[0]), .Y (mul_22_8_n_12));
  AND2XL mul_22_8_g2189(.A (in2[5]), .B (in1[1]), .Y (mul_22_8_n_11));
  AND2XL mul_22_8_g2190(.A (in2[9]), .B (in1[0]), .Y (mul_22_8_n_10));
  AND2XL mul_22_8_g2191(.A (in2[10]), .B (in1[0]), .Y (mul_22_8_n_9));
  AND2XL mul_22_8_g2192(.A (in2[4]), .B (in1[3]), .Y (mul_22_8_n_8));
  AND2XL mul_22_8_g2193(.A (in2[15]), .B (in1[0]), .Y (mul_22_8_n_7));
  AND2XL mul_22_8_g2194(.A (in2[3]), .B (in1[3]), .Y (mul_22_8_n_6));
  AND2XL mul_22_8_g2195(.A (in2[3]), .B (in1[2]), .Y (mul_22_8_n_5));
  AND2XL mul_22_8_g2196(.A (in2[1]), .B (in1[2]), .Y (mul_22_8_n_4));
  AND2XL mul_22_8_g2197(.A (in2[11]), .B (in1[2]), .Y (mul_22_8_n_3));
  AND2XL mul_22_8_g2198(.A (in2[11]), .B (in1[3]), .Y (mul_22_8_n_2));
  AND2XL mul_22_8_g2199(.A (in2[6]), .B (in1[3]), .Y (mul_22_8_n_1));
  AND2XL mul_22_8_g2200(.A (in2[7]), .B (in1[0]), .Y (mul_22_8_n_0));
endmodule


