`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Jan 27 2021 14:54:22 KST (Jan 27 2021 05:54:22 UTC)

module cache_Add_10Sx5S_11S_1(in2, in1, out1);
  input [9:0] in2;
  input [4:0] in1;
  output [10:0] out1;
  wire [9:0] in2;
  wire [4:0] in1;
  wire [10:0] out1;
  wire add_23_2_n_1, add_23_2_n_2, add_23_2_n_3, add_23_2_n_4,
       add_23_2_n_8, add_23_2_n_13, add_23_2_n_15, add_23_2_n_17;
  wire add_23_2_n_18, add_23_2_n_19, add_23_2_n_20, add_23_2_n_21,
       add_23_2_n_22, add_23_2_n_23, add_23_2_n_24, add_23_2_n_25;
  wire add_23_2_n_26, add_23_2_n_27, add_23_2_n_28, add_23_2_n_29,
       add_23_2_n_30, add_23_2_n_31, add_23_2_n_32, add_23_2_n_33;
  wire add_23_2_n_34, add_23_2_n_35, add_23_2_n_36, add_23_2_n_37,
       add_23_2_n_38, add_23_2_n_39, add_23_2_n_40, add_23_2_n_41;
  wire add_23_2_n_42, add_23_2_n_43, add_23_2_n_44, add_23_2_n_45,
       add_23_2_n_46, add_23_2_n_47, add_23_2_n_48, add_23_2_n_49;
  wire add_23_2_n_50, add_23_2_n_51, add_23_2_n_52, add_23_2_n_53,
       add_23_2_n_54, add_23_2_n_55, add_23_2_n_56, add_23_2_n_57;
  wire add_23_2_n_58, add_23_2_n_59, add_23_2_n_60, add_23_2_n_61,
       add_23_2_n_62, add_23_2_n_63, add_23_2_n_64, add_23_2_n_65;
  wire add_23_2_n_66, add_23_2_n_67, add_23_2_n_68, add_23_2_n_69,
       add_23_2_n_70, add_23_2_n_71, add_23_2_n_72, add_23_2_n_75;
  wire add_23_2_n_91, add_23_2_n_92, add_23_2_n_93, add_23_2_n_95,
       add_23_2_n_97, add_23_2_n_98, add_23_2_n_99, add_23_2_n_100;
  wire add_23_2_n_102, add_23_2_n_106, add_23_2_n_107, add_23_2_n_111,
       add_23_2_n_112, add_23_2_n_113, add_23_2_n_116;
  NOR2X1 add_23_2_g217(.A (add_23_2_n_34), .B (add_23_2_n_72), .Y
       (add_23_2_n_75));
  NOR2BX1 add_23_2_g218(.AN (add_23_2_n_54), .B (add_23_2_n_71), .Y
       (out1[10]));
  MXI2XL add_23_2_g219(.A (add_23_2_n_50), .B (add_23_2_n_51), .S0
       (add_23_2_n_112), .Y (out1[8]));
  NOR2X1 add_23_2_g223(.A (add_23_2_n_31), .B (add_23_2_n_70), .Y
       (add_23_2_n_72));
  NOR2X1 add_23_2_g224(.A (add_23_2_n_44), .B (add_23_2_n_111), .Y
       (add_23_2_n_71));
  NOR2X2 add_23_2_g225(.A (add_23_2_n_60), .B (add_23_2_n_66), .Y
       (add_23_2_n_70));
  NOR2BX1 add_23_2_g227(.AN (add_23_2_n_22), .B (add_23_2_n_67), .Y
       (add_23_2_n_69));
  NOR2X1 add_23_2_g230(.A (add_23_2_n_61), .B (add_23_2_n_65), .Y
       (add_23_2_n_68));
  NOR2X1 add_23_2_g232(.A (add_23_2_n_24), .B (add_23_2_n_106), .Y
       (add_23_2_n_67));
  NOR2X2 add_23_2_g233(.A (add_23_2_n_57), .B (add_23_2_n_63), .Y
       (add_23_2_n_66));
  NOR2X1 add_23_2_g234(.A (add_23_2_n_56), .B (add_23_2_n_106), .Y
       (add_23_2_n_65));
  NOR2BX1 add_23_2_g235(.AN (add_23_2_n_33), .B (add_23_2_n_3), .Y
       (add_23_2_n_64));
  NOR2X4 add_23_2_g237(.A (add_23_2_n_55), .B (add_23_2_n_62), .Y
       (add_23_2_n_63));
  NOR2X4 add_23_2_g239(.A (add_23_2_n_4), .B (add_23_2_n_59), .Y
       (add_23_2_n_62));
  OAI21X1 add_23_2_g240(.A0 (add_23_2_n_98), .A1 (add_23_2_n_53), .B0
       (add_23_2_n_25), .Y (add_23_2_n_61));
  OAI21X2 add_23_2_g241(.A0 (add_23_2_n_40), .A1 (add_23_2_n_53), .B0
       (add_23_2_n_52), .Y (add_23_2_n_60));
  NOR2X2 add_23_2_g242(.A (add_23_2_n_35), .B (add_23_2_n_58), .Y
       (add_23_2_n_59));
  NOR2X2 add_23_2_g244(.A (add_23_2_n_20), .B (add_23_2_n_28), .Y
       (add_23_2_n_58));
  NAND2X1 add_23_2_g246(.A (add_23_2_n_39), .B (add_23_2_n_45), .Y
       (add_23_2_n_57));
  NAND2BX1 add_23_2_g247(.AN (add_23_2_n_100), .B (add_23_2_n_45), .Y
       (add_23_2_n_56));
  OAI21X2 add_23_2_g248(.A0 (add_23_2_n_33), .A1 (add_23_2_n_27), .B0
       (add_23_2_n_29), .Y (add_23_2_n_55));
  AOI21X1 add_23_2_g249(.A0 (add_23_2_n_23), .A1 (add_23_2_n_34), .B0
       (add_23_2_n_36), .Y (add_23_2_n_54));
  NOR2X2 add_23_2_g251(.A (add_23_2_n_2), .B (add_23_2_n_38), .Y
       (add_23_2_n_53));
  AOI2BB1X1 add_23_2_g252(.A0N (add_23_2_n_25), .A1N (add_23_2_n_32),
       .B0 (add_23_2_n_1), .Y (add_23_2_n_52));
  INVX1 add_23_2_g253(.A (add_23_2_n_50), .Y (add_23_2_n_51));
  NAND2BX1 add_23_2_g259(.AN (add_23_2_n_31), .B (add_23_2_n_23), .Y
       (add_23_2_n_44));
  NOR2X1 add_23_2_g260(.A (add_23_2_n_34), .B (add_23_2_n_31), .Y
       (add_23_2_n_50));
  NOR2BX1 add_23_2_g261(.AN (add_23_2_n_29), .B (add_23_2_n_116), .Y
       (add_23_2_n_49));
  NOR2X1 add_23_2_g262(.A (add_23_2_n_1), .B (add_23_2_n_95), .Y
       (add_23_2_n_48));
  NAND2BX1 add_23_2_g263(.AN (add_23_2_n_97), .B (add_23_2_n_25), .Y
       (add_23_2_n_47));
  NOR2X1 add_23_2_g264(.A (add_23_2_n_2), .B (add_23_2_n_21), .Y
       (add_23_2_n_46));
  NOR2X1 add_23_2_g265(.A (add_23_2_n_21), .B (add_23_2_n_24), .Y
       (add_23_2_n_45));
  INVX1 add_23_2_g269(.A (add_23_2_n_39), .Y (add_23_2_n_40));
  NOR2X1 add_23_2_g272(.A (add_23_2_n_22), .B (add_23_2_n_21), .Y
       (add_23_2_n_38));
  NAND2BX1 add_23_2_g273(.AN (add_23_2_n_36), .B (add_23_2_n_23), .Y
       (add_23_2_n_43));
  NOR2X1 add_23_2_g274(.A (add_23_2_n_35), .B (add_23_2_n_28), .Y
       (add_23_2_n_37));
  NAND2BX1 add_23_2_g275(.AN (add_23_2_n_24), .B (add_23_2_n_22), .Y
       (add_23_2_n_42));
  NAND2X1 add_23_2_g276(.A (add_23_2_n_33), .B (add_23_2_n_26), .Y
       (add_23_2_n_41));
  NOR2X1 add_23_2_g277(.A (add_23_2_n_32), .B (add_23_2_n_30), .Y
       (add_23_2_n_39));
  NOR2X1 add_23_2_g280(.A (in2[9]), .B (in1[4]), .Y (add_23_2_n_36));
  NOR2X2 add_23_2_g281(.A (add_23_2_n_17), .B (add_23_2_n_18), .Y
       (add_23_2_n_35));
  AND2X1 add_23_2_g282(.A (in2[8]), .B (in1[4]), .Y (add_23_2_n_34));
  NAND2X2 add_23_2_g283(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_33));
  NOR2X2 add_23_2_g284(.A (in2[7]), .B (in1[4]), .Y (add_23_2_n_32));
  NOR2X1 add_23_2_g285(.A (in2[8]), .B (in1[4]), .Y (add_23_2_n_31));
  NOR2X1 add_23_2_g286(.A (in2[6]), .B (in1[4]), .Y (add_23_2_n_30));
  NAND2X1 add_23_2_g289(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_29));
  NOR2X8 add_23_2_g290(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_28));
  NOR2X8 add_23_2_g291(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_27));
  NAND2X2 add_23_2_g292(.A (add_23_2_n_102), .B (add_23_2_n_19), .Y
       (add_23_2_n_26));
  NAND2X1 add_23_2_g293(.A (in2[6]), .B (in1[4]), .Y (add_23_2_n_25));
  NOR2X1 add_23_2_g294(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_24));
  NAND2X1 add_23_2_g295(.A (in2[9]), .B (in1[4]), .Y (add_23_2_n_23));
  NAND2X1 add_23_2_g296(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_22));
  NOR2X2 add_23_2_g297(.A (in2[5]), .B (in1[4]), .Y (add_23_2_n_21));
  NAND2X4 add_23_2_g298(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_20));
  CLKINVX2 add_23_2_g299(.A (in1[2]), .Y (add_23_2_n_19));
  CLKINVX2 add_23_2_g300(.A (in1[1]), .Y (add_23_2_n_18));
  CLKINVX2 add_23_2_g301(.A (in2[1]), .Y (add_23_2_n_17));
  INVX1 add_23_2_g306(.A (in1[4]), .Y (add_23_2_n_15));
  XNOR2X1 add_23_2_g2(.A (add_23_2_n_20), .B (add_23_2_n_37), .Y
       (out1[1]));
  NOR2BX1 add_23_2_g307(.AN (add_23_2_n_53), .B (add_23_2_n_8), .Y
       (add_23_2_n_13));
  XNOR2X1 add_23_2_g308(.A (add_23_2_n_49), .B (add_23_2_n_64), .Y
       (out1[3]));
  XNOR2XL add_23_2_g309(.A (add_23_2_n_48), .B (add_23_2_n_68), .Y
       (out1[7]));
  CLKXOR2X1 add_23_2_g310(.A (add_23_2_n_47), .B (add_23_2_n_13), .Y
       (out1[6]));
  XNOR2XL add_23_2_g311(.A (add_23_2_n_46), .B (add_23_2_n_69), .Y
       (out1[5]));
  NOR2BX1 add_23_2_g312(.AN (add_23_2_n_45), .B (add_23_2_n_106), .Y
       (add_23_2_n_8));
  CLKXOR2X1 add_23_2_g313(.A (add_23_2_n_43), .B (add_23_2_n_75), .Y
       (out1[9]));
  CLKXOR2X1 add_23_2_g314(.A (add_23_2_n_42), .B (add_23_2_n_107), .Y
       (out1[4]));
  CLKXOR2X1 add_23_2_g315(.A (add_23_2_n_41), .B (add_23_2_n_91), .Y
       (out1[2]));
  NAND2BX4 add_23_2_g316(.AN (add_23_2_n_27), .B (add_23_2_n_26), .Y
       (add_23_2_n_4));
  NOR2BX1 add_23_2_g317(.AN (add_23_2_n_26), .B (add_23_2_n_92), .Y
       (add_23_2_n_3));
  NOR2BX1 add_23_2_g318(.AN (in2[5]), .B (add_23_2_n_15), .Y
       (add_23_2_n_2));
  NOR2BX1 add_23_2_g319(.AN (in2[7]), .B (add_23_2_n_15), .Y
       (add_23_2_n_1));
  CLKXOR2X1 add_23_2_g320(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  INVXL add_23_2_fopt(.A (add_23_2_n_93), .Y (add_23_2_n_91));
  INVXL add_23_2_fopt321(.A (add_23_2_n_93), .Y (add_23_2_n_92));
  INVXL add_23_2_fopt322(.A (add_23_2_n_59), .Y (add_23_2_n_93));
  BUFX2 add_23_2_fopt323(.A (add_23_2_n_32), .Y (add_23_2_n_95));
  INVXL add_23_2_fopt324(.A (add_23_2_n_99), .Y (add_23_2_n_97));
  INVXL add_23_2_fopt325(.A (add_23_2_n_99), .Y (add_23_2_n_98));
  INVXL add_23_2_fopt326(.A (add_23_2_n_100), .Y (add_23_2_n_99));
  BUFX2 add_23_2_fopt327(.A (add_23_2_n_30), .Y (add_23_2_n_100));
  CLKINVX3 add_23_2_fopt328(.A (in2[2]), .Y (add_23_2_n_102));
  BUFX2 add_23_2_fopt330(.A (add_23_2_n_106), .Y (add_23_2_n_107));
  BUFX3 add_23_2_fopt331(.A (add_23_2_n_63), .Y (add_23_2_n_106));
  INVXL add_23_2_fopt332(.A (add_23_2_n_113), .Y (add_23_2_n_111));
  INVXL add_23_2_fopt333(.A (add_23_2_n_113), .Y (add_23_2_n_112));
  INVXL add_23_2_fopt334(.A (add_23_2_n_70), .Y (add_23_2_n_113));
  BUFX2 add_23_2_fopt335(.A (add_23_2_n_27), .Y (add_23_2_n_116));
endmodule


