`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Jan 27 2021 13:48:47 KST (Jan 27 2021 04:48:47 UTC)

module cache_Eqi3u8_4_0(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire n_0, n_1;
  NOR3BXL g30(.AN (in1[1]), .B (n_1), .C (in1[2]), .Y (out1));
  NAND3BXL g31(.AN (in1[3]), .B (in1[0]), .C (n_0), .Y (n_1));
  NOR4X1 g32(.A (in1[7]), .B (in1[6]), .C (in1[5]), .D (in1[4]), .Y
       (n_0));
endmodule


