`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Dec 17 2020 14:24:44 KST (Dec 17 2020 05:24:44 UTC)

module cache_Mul2i10u16_4(in1, out1);
  input [15:0] in1;
  output [19:0] out1;
  wire [15:0] in1;
  wire [19:0] out1;
  wire const_mul_20_8_n_1, const_mul_20_8_n_3, const_mul_20_8_n_5,
       const_mul_20_8_n_7, const_mul_20_8_n_9, const_mul_20_8_n_11,
       const_mul_20_8_n_13, const_mul_20_8_n_15;
  wire const_mul_20_8_n_17, const_mul_20_8_n_19, const_mul_20_8_n_21,
       const_mul_20_8_n_23, const_mul_20_8_n_25, const_mul_20_8_n_27,
       const_mul_20_8_n_29;
  assign out1[0] = 1'b0;
  assign out1[1] = in1[0];
  assign out1[2] = in1[1];
  ADDHX1 const_mul_20_8_g313(.A (in1[15]), .B (const_mul_20_8_n_29),
       .CO (out1[19]), .S (out1[18]));
  ADDHX1 const_mul_20_8_g314(.A (in1[14]), .B (const_mul_20_8_n_27),
       .CO (const_mul_20_8_n_29), .S (out1[17]));
  ADDFX1 const_mul_20_8_g315(.A (const_mul_20_8_n_25), .B (in1[13]),
       .CI (in1[15]), .CO (const_mul_20_8_n_27), .S (out1[16]));
  ADDFX1 const_mul_20_8_g316(.A (const_mul_20_8_n_23), .B (in1[12]),
       .CI (in1[14]), .CO (const_mul_20_8_n_25), .S (out1[15]));
  ADDFX1 const_mul_20_8_g317(.A (const_mul_20_8_n_21), .B (in1[11]),
       .CI (in1[13]), .CO (const_mul_20_8_n_23), .S (out1[14]));
  ADDFX1 const_mul_20_8_g318(.A (const_mul_20_8_n_19), .B (in1[10]),
       .CI (in1[12]), .CO (const_mul_20_8_n_21), .S (out1[13]));
  ADDFX1 const_mul_20_8_g319(.A (const_mul_20_8_n_17), .B (in1[9]), .CI
       (in1[11]), .CO (const_mul_20_8_n_19), .S (out1[12]));
  ADDFX1 const_mul_20_8_g320(.A (const_mul_20_8_n_15), .B (in1[8]), .CI
       (in1[10]), .CO (const_mul_20_8_n_17), .S (out1[11]));
  ADDFX1 const_mul_20_8_g321(.A (const_mul_20_8_n_13), .B (in1[7]), .CI
       (in1[9]), .CO (const_mul_20_8_n_15), .S (out1[10]));
  ADDFX1 const_mul_20_8_g322(.A (const_mul_20_8_n_11), .B (in1[6]), .CI
       (in1[8]), .CO (const_mul_20_8_n_13), .S (out1[9]));
  ADDFX1 const_mul_20_8_g323(.A (const_mul_20_8_n_9), .B (in1[5]), .CI
       (in1[7]), .CO (const_mul_20_8_n_11), .S (out1[8]));
  ADDFX1 const_mul_20_8_g324(.A (const_mul_20_8_n_7), .B (in1[4]), .CI
       (in1[6]), .CO (const_mul_20_8_n_9), .S (out1[7]));
  ADDFX1 const_mul_20_8_g325(.A (const_mul_20_8_n_5), .B (in1[3]), .CI
       (in1[5]), .CO (const_mul_20_8_n_7), .S (out1[6]));
  ADDFX1 const_mul_20_8_g326(.A (const_mul_20_8_n_3), .B (in1[2]), .CI
       (in1[4]), .CO (const_mul_20_8_n_5), .S (out1[5]));
  ADDFX1 const_mul_20_8_g327(.A (const_mul_20_8_n_1), .B (in1[1]), .CI
       (in1[3]), .CO (const_mul_20_8_n_3), .S (out1[4]));
  ADDHX1 const_mul_20_8_g328(.A (in1[2]), .B (in1[0]), .CO
       (const_mul_20_8_n_1), .S (out1[3]));
endmodule


