`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Jan 27 2021 17:56:25 KST (Jan 27 2021 08:56:25 UTC)

module mac_N_Mux_18_2_2_1(in3, in2, ctrl1, out1);
  input [17:0] in3, in2;
  input ctrl1;
  output [17:0] out1;
  wire [17:0] in3, in2;
  wire ctrl1;
  wire [17:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35;
  OAI21X4 g181(.A0 (ctrl1), .A1 (n_13), .B0 (n_24), .Y (out1[9]));
  OAI21X4 g193(.A0 (ctrl1), .A1 (n_11), .B0 (n_35), .Y (out1[16]));
  OAI21X4 g194(.A0 (ctrl1), .A1 (n_8), .B0 (n_26), .Y (out1[15]));
  OAI21X4 g182(.A0 (ctrl1), .A1 (n_0), .B0 (n_31), .Y (out1[14]));
  OAI21X4 g188(.A0 (ctrl1), .A1 (n_5), .B0 (n_32), .Y (out1[13]));
  OAI21X4 g195(.A0 (ctrl1), .A1 (n_3), .B0 (n_34), .Y (out1[12]));
  OAI21X4 g183(.A0 (ctrl1), .A1 (n_4), .B0 (n_29), .Y (out1[11]));
  OAI21X4 g185(.A0 (ctrl1), .A1 (n_17), .B0 (n_22), .Y (out1[10]));
  OAI21X4 g189(.A0 (ctrl1), .A1 (n_16), .B0 (n_33), .Y (out1[17]));
  OAI21X4 g191(.A0 (ctrl1), .A1 (n_10), .B0 (n_25), .Y (out1[0]));
  OAI21X4 g196(.A0 (ctrl1), .A1 (n_6), .B0 (n_19), .Y (out1[7]));
  OAI21X4 g197(.A0 (ctrl1), .A1 (n_2), .B0 (n_28), .Y (out1[6]));
  OAI21X4 g190(.A0 (ctrl1), .A1 (n_15), .B0 (n_27), .Y (out1[5]));
  OAI21X4 g184(.A0 (ctrl1), .A1 (n_1), .B0 (n_23), .Y (out1[4]));
  OAI21X4 g186(.A0 (ctrl1), .A1 (n_7), .B0 (n_18), .Y (out1[3]));
  OAI21X4 g187(.A0 (ctrl1), .A1 (n_12), .B0 (n_20), .Y (out1[2]));
  OAI21X4 g198(.A0 (ctrl1), .A1 (n_9), .B0 (n_30), .Y (out1[1]));
  OAI21X4 g192(.A0 (ctrl1), .A1 (n_14), .B0 (n_21), .Y (out1[8]));
  NAND2X8 g200(.A (in2[16]), .B (ctrl1), .Y (n_35));
  NAND2X8 g215(.A (in2[12]), .B (ctrl1), .Y (n_34));
  NAND2X8 g207(.A (in2[17]), .B (ctrl1), .Y (n_33));
  NAND2X8 g211(.A (in2[13]), .B (ctrl1), .Y (n_32));
  NAND2X8 g203(.A (in2[14]), .B (ctrl1), .Y (n_31));
  NAND2X8 g216(.A (in2[1]), .B (ctrl1), .Y (n_30));
  NAND2X8 g201(.A (in2[11]), .B (ctrl1), .Y (n_29));
  NAND2X8 g208(.A (in2[6]), .B (ctrl1), .Y (n_28));
  NAND2X8 g199(.A (in2[5]), .B (ctrl1), .Y (n_27));
  NAND2X8 g214(.A (in2[15]), .B (ctrl1), .Y (n_26));
  NAND2X8 g210(.A (in2[0]), .B (ctrl1), .Y (n_25));
  NAND2X8 g209(.A (in2[9]), .B (ctrl1), .Y (n_24));
  NAND2X8 g202(.A (in2[4]), .B (ctrl1), .Y (n_23));
  NAND2X8 g205(.A (in2[10]), .B (ctrl1), .Y (n_22));
  NAND2X8 g212(.A (in2[8]), .B (ctrl1), .Y (n_21));
  NAND2X8 g206(.A (in2[2]), .B (ctrl1), .Y (n_20));
  NAND2X8 g213(.A (in2[7]), .B (ctrl1), .Y (n_19));
  NAND2X8 g204(.A (in2[3]), .B (ctrl1), .Y (n_18));
  CLKINVX4 g219(.A (in3[10]), .Y (n_17));
  CLKINVX4 g234(.A (in3[17]), .Y (n_16));
  CLKINVX4 g228(.A (in3[5]), .Y (n_15));
  CLKINVX4 g232(.A (in3[8]), .Y (n_14));
  CLKINVX4 g231(.A (in3[9]), .Y (n_13));
  CLKINVX4 g222(.A (in3[2]), .Y (n_12));
  CLKINVX4 g217(.A (in3[16]), .Y (n_11));
  CLKINVX4 g218(.A (in3[0]), .Y (n_10));
  CLKINVX4 g226(.A (in3[1]), .Y (n_9));
  CLKINVX4 g233(.A (in3[15]), .Y (n_8));
  CLKINVX4 g221(.A (in3[3]), .Y (n_7));
  CLKINVX4 g223(.A (in3[7]), .Y (n_6));
  CLKINVX4 g224(.A (in3[13]), .Y (n_5));
  CLKINVX4 g225(.A (in3[11]), .Y (n_4));
  CLKINVX4 g230(.A (in3[12]), .Y (n_3));
  CLKINVX4 g227(.A (in3[6]), .Y (n_2));
  CLKINVX4 g229(.A (in3[4]), .Y (n_1));
  CLKINVX4 g220(.A (in3[14]), .Y (n_0));
endmodule


